DELETE FROM yc_site_column;
INSERT INTO yc_site_column VALUES ('100000','physicalplansiteid',100000,'VARCHAR(64)','physicalplansiteid','0','Physical Plan<br>Site ID','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100030','longitude',100030,'DECIMAL(10,7)','longitude','4','LONG','2',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100060','latitude',100060,'DECIMAL(10,7)','latitude','4','LAT','2',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100090','areatype',100090,'VARCHAR(100)','areatype','0','Area Type','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100120','sitetype',100120,'VARCHAR(100)','sitetype','0','Site Type','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100150','newsitetype',100150,'VARCHAR(100)','newsitetype','0','New<br>Site Type','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100180','syear',100180,'VARCHAR(100)','syear','0','Year','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100210','bands',100210,'VARCHAR(100)','bands','0','Bands','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100240','region',100240,'VARCHAR(100)','region','0','Region','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100270','province',100270,'VARCHAR(100)','province','0','Province','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100300','city',100300,'VARCHAR(100)','city','0','City/Municipality','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100330','barangay',100330,'VARCHAR(100)','barangay','0','Barangay','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100360','area',100360,'VARCHAR(100)','area','0','Area','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100390','brgycode',100390,'VARCHAR(100)','brgycode','0','brgy_code','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100420','brgypop',100420,'DECIMAL(10,0)','brgypop','1','brgy_pop','2',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100450','height',100450,'DECIMAL(10,0)','height','1','Height<br>(m)','2',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100480','towertype',100480,'VARCHAR(100)','towertype','0','Tower Type','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100510','cohoming',100510,'VARCHAR(100)','cohoming','0','CO<br>Homing','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100540','distance',100540,'DECIMAL(19,10)','distance','4','Distance<br>(km)','2',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100570','snnn',100570,'VARCHAR(100)','snnn','0','S/N','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100600','spriority',100600,'VARCHAR(100)','spriority','0','Priority','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100630','phasebaseline',100630,'VARCHAR(100)','phasebaseline','0','Phase(baseline)','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100660','phase2020v1',100660,'VARCHAR(100)','phase2020v1','0','Phase<br>(2020_v1)','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100690','phase2020v2',100690,'VARCHAR(100)','phase2020v2','0','Phase<br>(2020_v2)','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100720','friendlysite',100720,'VARCHAR(100)','friendlysite','0','Friendly<br>Site','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100750','saqclustering',100750,'VARCHAR(100)','saqclustering','0','SAQ<br>Clustering','0',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100780','saqvendor',100780,'VARCHAR(100)','saqvendor','0','SAQ Vendor','0',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100810','saqponumber',100810,'VARCHAR(100)','saqponumber','0','SAQ PO Number','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100840','saqpobatch',100840,'VARCHAR(100)','saqpobatch','0','SAQ PO Batch','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100870','tssdddvendor',100870,'VARCHAR(100)','tssdddvendor','0','TSS/DDD Vendor','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100900','tssdddponumber',100900,'VARCHAR(100)','tssdddponumber','0','TSS/DDD PO Number','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100930','cmevendor',100930,'VARCHAR(100)','cmevendor','0','CME Vendor','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100960','cmeponumber',100960,'VARCHAR(100)','cmeponumber','0','CME PO Number','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100990','sarfissued',100990,'DATETIME','sarfissued','2','SARF Issued','2','Site Hunting/Site Survey','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101020','surveydoneplan',101020,'DATETIME','surveydoneplan','2','Survey Done<br>Plan','2','Site Hunting/Site Survey','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101050','surverydoneactual',101050,'DATETIME','surverydoneactual','2','Survery Done<br>Actual','2','Site Hunting/Site Survey','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101080','submittedplan',101080,'DATETIME','submittedplan','2','Submitted<br>Plan','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101110','submittedoptiona',101110,'DATETIME','submittedoptiona','2','Submitted<br>Option A','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101140','submittedoptionb',101140,'DATETIME','submittedoptionb','2','Submitted<br>Option B','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101170','submittedoptionc',101170,'DATETIME','submittedoptionc','2','Submitted<br>Option C','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101200','submittedoptiond',101200,'DATETIME','submittedoptiond','2','Submitted<br>Option D','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101230','submittedactual',101230,'DATETIME','submittedactual','2','Submitted<br>Actual','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101260','reviewedoptiona',101260,'DATETIME','reviewedoptiona','2','Reviewed<br>Option A','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101290','reviewedoptionb',101290,'DATETIME','reviewedoptionb','2','Reviewed<br>Option B','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101320','reviewedoptionc',101320,'DATETIME','reviewedoptionc','2','Reviewed<br>Option C','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101350','reviewedoptiond',101350,'DATETIME','reviewedoptiond','2','Reviewed<br>Option D','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101380','reviewedactual',101380,'DATETIME','reviewedactual','2','Reviewed<br>Actual','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101410','sarremarks',101410,'VARCHAR(200)','sarremarks','0','SAR<br>Remarks','1','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101440','revision1st',101440,'DATETIME','revision1st','2','1st<br>Revision','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101470','revision2nd',101470,'DATETIME','revision2nd','2','2nd<br>Revision','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101500','approvedplan',101500,'DATETIME','approvedplan','2','Approved<br>Plan','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101530','approvedoptiona',101530,'DATETIME','approvedoptiona','2','Approved<br>Option A','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101560','approvedoptionb',101560,'DATETIME','approvedoptionb','2','Approved<br>Option B','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101590','approvedoptionc',101590,'DATETIME','approvedoptionc','2','Approved<br>Option C','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101620','approvedoptiond',101620,'DATETIME','approvedoptiond','2','Approved<br>Option D','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101650','approvedactual',101650,'DATETIME','approvedactual','2','Approved<br>Actual','2','Site Acquisition Report (SAR)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101680','mocsignedoptiona',101680,'DATETIME','mocsignedoptiona','2','MOC Signed<br>Option A','2','Memorandum of Conformity (MOC)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101710','mocsignedoptionb',101710,'DATETIME','mocsignedoptionb','2','MOC Signed<br>Option B','2','Memorandum of Conformity (MOC)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101740','mocsignedoptionc',101740,'DATETIME','mocsignedoptionc','2','MOC Signed<br>Option C','2','Memorandum of Conformity (MOC)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101770','mocsignedoptiond',101770,'DATETIME','mocsignedoptiond','2','MOC Signed<br>Option D','2','Memorandum of Conformity (MOC)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101800','mocsignedactual',101800,'DATETIME','mocsignedactual','2','MOC Signed<br>Actual','2','Memorandum of Conformity (MOC)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101830','mocsubmittedactual',101830,'DATETIME','mocsubmittedactual','2','MOC Submitted<br>Actual','2','Memorandum of Conformity (MOC)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101860','mocapprovedplan',101860,'DATETIME','mocapprovedplan','2','MOC Approved<br>Plan','2','Memorandum of Conformity (MOC)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101890','mocapprovedactual',101890,'DATETIME','mocapprovedactual','2','MOC Approved<br>Actual','2','Memorandum of Conformity (MOC)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101920','mocforrenego',101920,'VARCHAR(100)','mocforrenego','0','MOC for Renego','1','Memorandum of Conformity (MOC)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101950','mocremarks',101950,'VARCHAR(200)','mocremarks','0','MOC Remarks','1','Memorandum of Conformity (MOC)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101980','nrafsubmittedactual',101980,'DATETIME','nrafsubmittedactual','2','NRAF Submitted<br>Actual','2','Memorandum of Conformity (MOC)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102010','nrafapprovedactual',102010,'DATETIME','nrafapprovedactual','2','NRAF Approved<br>Actual','2','Memorandum of Conformity (MOC)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102040','approvedoption',102040,'VARCHAR(100)','approvedoption','0','Approved<br>Option','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102070','lessorname',102070,'VARCHAR(100)','lessorname','0','Lessor Name','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102100','siteaddress',102100,'VARCHAR(100)','siteaddress','0','Site Address','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102130','streetbuilding',102130,'VARCHAR(100)','streetbuilding','0','Street/Building','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102160','actbarangay',102160,'VARCHAR(100)','actbarangay','0','Barangay','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102190','citymunicipality',102190,'VARCHAR(100)','citymunicipality','0','City/Municipality','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102220','actprovince',102220,'VARCHAR(100)','actprovince','0','Province','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102250','actlongitude',102250,'DECIMAL(10,7)','actlongitude','4','LONG','2','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102280','actlatitude',102280,'DECIMAL(10,7)','actlatitude','4','LAT','2','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102310','actsitetype',102310,'VARCHAR(100)','actsitetype','0','Site Type','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102340','altitude',102340,'DECIMAL(10,0)','altitude','1','Altitude','2','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102370','buildingheight',102370,'DECIMAL(10,0)','buildingheight','1','Building Height (RT)','2','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102400','periodoflease',102400,'VARCHAR(100)','periodoflease','0','Period of<br>Lease','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102430','monthlyrent',102430,'VARCHAR(100)','monthlyrent','0','Monthly<br>Rent','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102460','payment',102460,'VARCHAR(100)','payment','0','Payment','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102490','leasearea',102490,'VARCHAR(100)','leasearea','0','Lease Area','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102520','advancerental',102520,'VARCHAR(100)','advancerental','0','Advance<br>Rental','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102550','securitydeposit',102550,'VARCHAR(100)','securitydeposit','0','Security<br>Deposit','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102580','escalationrate',102580,'VARCHAR(100)','escalationrate','0','Escalation<br>Rate','1','Actual Site Information / Negotiation & Review Approval Form (NRAF) Details','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102610','neighborsactual',102610,'DATETIME','neighborsactual','2','Neighbors<br>Actual','2','Social Acceptability/Barangay Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102640','noneighborsactual',102640,'DATETIME','noneighborsactual','2','No Neighbors<br>Actual','2','Social Acceptability/Barangay Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102670','nameofsubdivisionhoa',102670,'DATETIME','nameofsubdivisionhoa','2','Name of<br>Subdivision/HOA','2','Social Acceptability/Barangay Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102700','nameofhoapresident',102700,'DATETIME','nameofhoapresident','2','Name of<br>HOA President','2','Social Acceptability/Barangay Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102730','hoapresidentcontactno',102730,'DATETIME','hoapresidentcontactno','2','HOA President Contact No.','2','Social Acceptability/Barangay Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102760','hoaclearancesecured',102760,'DATETIME','hoaclearancesecured','2','HOA Clearance<br>Secured','2','Social Acceptability/Barangay Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102790','brgyclearanceplan',102790,'DATETIME','brgyclearanceplan','2','BrgyClearance<br>Plan','2','Social Acceptability/Barangay Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102820','brgyclearanceapplied',102820,'DATETIME','brgyclearanceapplied','2','BrgyClearance<br>Applied','2','Social Acceptability/Barangay Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102850','brgyclearanceactual',102850,'DATETIME','brgyclearanceactual','2','BrgyClearance<br>Actual','2','Social Acceptability/Barangay Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102880','brgyresolutionapplied',102880,'DATETIME','brgyresolutionapplied','2','BrgyResolution<br>Applied','2','Social Acceptability/Barangay Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102910','brgyresolutionplan',102910,'DATETIME','brgyresolutionplan','2','BrgyResolution<br>Plan','2','Social Acceptability/Barangay Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102970','propertydocsplan',102970,'DATETIME','propertydocsplan','2','Property Docs<br>Plan','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103000','taxdeclarationsecured',103000,'DATETIME','taxdeclarationsecured','2','Tax Declaration<br>Secured','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103030','taxclearancesecured',103030,'DATETIME','taxclearancesecured','2','Tax Clearance<br>Secured','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103060','tctsecured',103060,'DATETIME','tctsecured','2','TCT<br>Secured','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103090','segregationplansigned',103090,'DATETIME','segregationplansigned','2','Segregation Plan Signed','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103120','conceptualdrawingsigned',103120,'DATETIME','conceptualdrawingsigned','2','Conceptual Drawing Signed','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103150','otherdocuments',103150,'VARCHAR(100)','otherdocuments','0','Other Documents','1','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103180','tpcaspca',103180,'VARCHAR(100)','tpcaspca','0','TPCA / SPCA','1','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103210','tinnn',103210,'VARCHAR(100)','tinnn','0','TIN','1','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103240','bankaccountname',103240,'VARCHAR(100)','bankaccountname','0','Bank Account Name','1','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103270','banknamebranch',103270,'VARCHAR(100)','banknamebranch','0','Bank Name/Branch','1','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103300','bankaccountnumber',103300,'VARCHAR(100)','bankaccountnumber','0','Bank Account Number','1','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103330','lessorcontact',103330,'VARCHAR(100)','lessorcontact','0','Lessor Contact','1','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103360','lessoraddress',103360,'VARCHAR(100)','lessoraddress','0','Lessor Address','1','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103420','landclassification',103420,'VARCHAR(100)','landclassification','0','Land Classification','1','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103450','existingbuildingpermitforrtsite',103450,'VARCHAR(100)','existingbuildingpermitforrtsite','0','Existing Building Permit for RT site','1','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103480','asbuiltplanforrtsite',103480,'DATETIME','asbuiltplanforrtsite','2','As-Built Plan for RT Site','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103540','leasepackageplan',103540,'DATETIME','leasepackageplan','2','Lease Package<br>Plan','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103570','lessorid',103570,'VARCHAR(100)','lessorid','0','Lessor ID','1','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103600','propertydocscompleted',103600,'DATETIME','propertydocscompleted','2','Property Docs<br>Completed','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103660','draftcolplan',103660,'DATETIME','draftcolplan','2','Draft COL<br>Plan','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103690','draftcolsigned',103690,'DATETIME','draftcolsigned','2','Draft COL Signed','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103720','colapproved',103720,'DATETIME','colapproved','2','COL Approved','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103750','crafsubmittedactual',103750,'DATETIME','crafsubmittedactual','2','CRAF Submitted<br>Actual','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103780','crafapprovedactual',103780,'DATETIME','crafapprovedactual','2','CRAF Approved<br>Actual','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103810','colsignedbydito',103810,'DATETIME','colsignedbydito','2','COL Signed<br>by DITO','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103840','colsignedbylessor',103840,'DATETIME','colsignedbylessor','2','COL Signed<br>by Lessor','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103870','colsignedplan',103870,'DATETIME','colsignedplan','2','COL Signed<br>Plan','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103900','colsignedactual',103900,'DATETIME','colsignedactual','2','COL Signed<br>Actual','2','Property Documents/Site Lease','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103930','rfpsubmittedbyvendor',103930,'DATETIME','rfpsubmittedbyvendor','2','RFP Submitted<br>by Vendor','2','Request for Payment','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103960','rfpapproved',103960,'DATETIME','rfpapproved','2','RFP<br>Approved','2','Request for Payment','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103990','rentalpaidplan',103990,'DATETIME','rentalpaidplan','2','Rental Paid<br>Plan','2','Request for Payment','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104020','releasedchequetovendor',104020,'DATETIME','releasedchequetovendor','2','Released Cheque to Vendor','2','Request for Payment','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104050','releasedchequetolessor',104050,'DATETIME','releasedchequetolessor','2','Released Cheque to Lessor','2','Request for Payment','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104080','arorsubmittedtodito',104080,'DATETIME','arorsubmittedtodito','2','AR/OR Submitted to Dito','2','Request for Payment','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104110','rpremarks',104110,'VARCHAR(200)','rpremarks','0','Remarks','1','Request for Payment','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104140','sbtsidoneplan',104140,'DATETIME','sbtsidoneplan','2','SBT/SI Done<br>Plan','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104170','sbtsidoneactual',104170,'DATETIME','sbtsidoneactual','2','SBT/SI Done<br>Actual','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104200','sbtsireportplan',104200,'DATETIME','sbtsireportplan','2','SBT/SI Report<br>Plan','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104230','sbtsireportsubmitted',104230,'DATETIME','sbtsireportsubmitted','2','SBT/SI Report<br>Submitted','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104260','sbtsireportapproved',104260,'DATETIME','sbtsireportapproved','2','SBT/SI Report<br>Approved','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104290','tssdoneplan',104290,'DATETIME','tssdoneplan','2','TSS Done<br>Plan','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104320','tssdoneactual',104320,'DATETIME','tssdoneactual','2','TSS Done<br>Actual','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104350','tssrsubmittedplan',104350,'DATETIME','tssrsubmittedplan','2','TSSR Submitted<br>Plan','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104380','tssrsubmittedactual',104380,'DATETIME','tssrsubmittedactual','2','TSSR Submitted<br>Actual','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104410','tssrapprovedactual',104410,'DATETIME','tssrapprovedactual','2','TSSR Approved<br>Actual','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104440','dddsubmittedplan',104440,'DATETIME','dddsubmittedplan','2','DDD Submitted<br>Plan','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104470','prelimdddsubmitted',104470,'DATETIME','prelimdddsubmitted','2','Prelim DDD Submitted','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104500','prelimdddapproved',104500,'DATETIME','prelimdddapproved','2','Prelim DDD Approved','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104530','dddsubmittedactual',104530,'DATETIME','dddsubmittedactual','2','DDD Submitted<br>Actual','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104560','dddapprovedplan',104560,'DATETIME','dddapprovedplan','2','DDD Approved<br>Plan','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104590','dddapprovedactual',104590,'DATETIME','dddapprovedactual','2','DDD Approved<br>Actual','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104620','sttowertype',104620,'VARCHAR(100)','sttowertype','0','Tower<br>Type','1','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104650','tower',104650,'DECIMAL(10,7)','tower','4','Tower<br>(m)','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104680','towerordering',104680,'VARCHAR(100)','towerordering','0','Tower<br>Ordering','1','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104710','towerdeliveryonsiteplan',104710,'DATETIME','towerdeliveryonsiteplan','2','Tower Delivery on Site_Plan','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104740','towerdeliveryonsiteactual',104740,'DATETIME','towerdeliveryonsiteactual','2','Tower Delivery on Site_Actual','2','Site Engineering/Technical Site Survey/Tower Delivery','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104830','nationalpermitplan',104830,'DATETIME','nationalpermitplan','2','National Permit<br>Plan','2','National Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104860','denrcncapplied',104860,'DATETIME','denrcncapplied','2','DENR-CNC<br>Applied','2','National Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104890','denrcncacquired',104890,'DATETIME','denrcncacquired','2','DENR-CNC<br>Acquired','2','National Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104920','dohapplied',104920,'DATETIME','dohapplied','2','DOH<br>Applied','2','National Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104950','dohacquired',104950,'DATETIME','dohacquired','2','DOH<br>Acquired','2','National Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104980','atocaapapplied',104980,'DATETIME','atocaapapplied','2','ATO/CAAP<br>Applied','2','National Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105010','atocaapacquired',105010,'DATETIME','atocaapacquired','2','ATO/CAAP<br>Acquired','2','National Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105040','natlcompletedplan',105040,'DATETIME','natlcompletedplan','2','Natl Completed<br>Plan','2','National Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105070','lgupermitplan',105070,'DATETIME','lgupermitplan','2','LGU Permit<br>Plan','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105220','sbspresolutionapplied',105220,'DATETIME','sbspresolutionapplied','2','SB/SP Resolution<br>Applied','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105250','sbspresolutionacquired',105250,'DATETIME','sbspresolutionacquired','2','SB/SP Resolution<br>Acquired','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105280','mayorspermitsecured',105280,'DATETIME','mayorspermitsecured','2','Mayors Permit<br>Secured','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105310','lczoningapplied',105310,'DATETIME','lczoningapplied','2','LC/Zoning<br>Applied','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105340','zoningacquired',105340,'DATETIME','zoningacquired','2','Zoning<br>Acquired','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105370','locationalacquired',105370,'DATETIME','locationalacquired','2','Locational<br>Acquired','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105400','buildingpermitapplied',105400,'DATETIME','buildingpermitapplied','2','Building Permit<br>Applied','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105430','buildingpermitsecured',105430,'DATETIME','buildingpermitsecured','2','Building Permit<br>Secured','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105460','electricalpermitapplied',105460,'DATETIME','electricalpermitapplied','2','Electrical Permit<br>Applied','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105490','electricalpermitsecured',105490,'DATETIME','electricalpermitsecured','2','Electrical Permit<br>Secured','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105520','mechanicalpermitapplied',105520,'DATETIME','mechanicalpermitapplied','2','Mechanical Permit<br>Applied','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105550','mechanicalpermitsecured',105550,'DATETIME','mechanicalpermitsecured','2','Mechanical Permit<br>Secured','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105580','electronicspermitapplied',105580,'DATETIME','electronicspermitapplied','2','Electronics Permit<br>Applied','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105610','electronicspermitsecured',105610,'DATETIME','electronicspermitsecured','2','Electronics Permit<br>Secured','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105640','fencingpermitapplied',105640,'DATETIME','fencingpermitapplied','2','Fencing Permit<br>Applied','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105670','fencingpermitsecured',105670,'DATETIME','fencingpermitsecured','2','Fencing Permit<br>Secured','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105700','sanitarypermitapplied',105700,'DATETIME','sanitarypermitapplied','2','Sanitary Permit<br>Applied','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105730','sanitarypermitsecured',105730,'DATETIME','sanitarypermitsecured','2','Sanitary Permit<br>Secured','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105760','fsecapplied',105760,'DATETIME','fsecapplied','2','FSEC<br>Applied','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105790','fsecacquired',105790,'DATETIME','fsecacquired','2','FSEC<br>Acquired','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105820','lgucompletedplan',105820,'DATETIME','lgucompletedplan','2','LGU Completed<br>Plan','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105850','bom',105850,'DATETIME','bom','2','BOM','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105880','copyofbpor',105880,'DATETIME','copyofbpor','2','Copy of BP OR','2','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105910','ppremarks',105910,'VARCHAR(200)','ppremarks','0','Remarks','1','Pre-Construction Permitting(LGU)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105940','rtbdeclaredplan',105940,'DATETIME','rtbdeclaredplan','2','RTB Declared<br>Plan','2','Ready to Build','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105970','rtbdeclaredactual',105970,'DATETIME','rtbdeclaredactual','2','RTB Declared<br>Actual','2','Ready to Build','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106000','cfeiapplied',106000,'DATETIME','cfeiapplied','2','CFEI<br>Applied','2','Post-Construction Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106030','cfeiacquired',106030,'DATETIME','cfeiacquired','2','CFEI<br>Acquired','2','Post-Construction Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106060','occupancypermitapplied',106060,'DATETIME','occupancypermitapplied','2','Occupancy Permit<br>Applied','2','Post-Construction Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106090','occupancypermitsecured',106090,'DATETIME','occupancypermitsecured','2','Occupancy Permit<br>Secured','2','Post-Construction Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106120','fsicapplied',106120,'DATETIME','fsicapplied','2','FSIC<br>Applied','2','Post-Construction Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106150','fsicacquired',106150,'DATETIME','fsicacquired','2','FSIC<br>Acquired','2','Post-Construction Permitting','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106180','skomactual',106180,'DATETIME','skomactual','2','SKOM<br>Actual','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106210','mobilizationplan',106210,'DATETIME','mobilizationplan','2','Mobilization<br>Plan','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106240','mobilizationactual',106240,'DATETIME','mobilizationactual','2','Mobilization<br>Actual','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106270','excavationplan',106270,'DATETIME','excavationplan','2','Excavation<br>Plan','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106300','excavationactual',106300,'DATETIME','excavationactual','2','Excavation<br>Actual','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106330','leanconcretecompletion',106330,'DATETIME','leanconcretecompletion','2','Lean Concrete Completion','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106360','rebarsplan',106360,'DATETIME','rebarsplan','2','Rebars<br>Plan','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106390','rebarinstallation',106390,'DATETIME','rebarinstallation','2','Rebar Installation','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106420','rebartesting',106420,'DATETIME','rebartesting','2','Rebar<br>Testing','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106450','rebarinspection',106450,'DATETIME','rebarinspection','2','Rebar<br>Inspection','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106480','concreteplan',106480,'DATETIME','concreteplan','2','Concrete<br>Plan','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106510','concretepouringcompleted',106510,'DATETIME','concretepouringcompleted','2','Concrete Pouring Completed','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106540','concretetesting',106540,'DATETIME','concretetesting','2','Concrete Testing','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106570','backfillingplan',106570,'DATETIME','backfillingplan','2','Back Filling<br>Plan','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106600','backfillingactual',106600,'DATETIME','backfillingactual','2','Back Filling<br>Actual','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106630','odupadstarted',106630,'DATETIME','odupadstarted','2','ODU Pad<br>Started','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106660','odupadcompleted',106660,'DATETIME','odupadcompleted','2','ODU Pad<br>Completed','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106690','electricalgroundingplan',106690,'DATETIME','electricalgroundingplan','2','Electrical Grounding<br>Plan','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106720','electricalworksactual',106720,'DATETIME','electricalworksactual','2','Electrical Works<br>Actual','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106750','towererectionstarted',106750,'DATETIME','towererectionstarted','2','Tower Erection Started','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106780','towererectionplan',106780,'DATETIME','towererectionplan','2','Tower Erection<br>Plan','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106810','towererectioncompleted',106810,'DATETIME','towererectioncompleted','2','Tower Erection Completed','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106840','towerverticality',106840,'DATETIME','towerverticality','2','Tower<br>Verticality','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106870','sitedevworkscompleted',106870,'DATETIME','sitedevworkscompleted','2','Site Dev Works<br>Completed (RFI)','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106900','tempopowerplan',106900,'DATETIME','tempopowerplan','2','Tempo Power<br>Plan','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106930','tempopowerconnected',106930,'DATETIME','tempopowerconnected','2','Tempo Power Connected','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106960','rftiplan',106960,'DATETIME','rftiplan','2','RFTI<br>Plan','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106990','rftiactual',106990,'DATETIME','rftiactual','2','RFTI<br>Actual','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107020','prepatactual',107020,'DATETIME','prepatactual','2','Pre-PAT<br>Actual','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107050','patplan',107050,'DATETIME','patplan','2','PAT<br>Plan','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107080','patpassedactual',107080,'DATETIME','patpassedactual','2','PAT Passed<br>Actual','2','Civil Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107110','txsolution',107110,'DATETIME','txsolution','2','TX Solution','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107140','txinstalledactual',107140,'DATETIME','txinstalledactual','2','TX Installed<br>Actual','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107170','mosplan',107170,'DATETIME','mosplan','2','MOS<br>Plan','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107200','mosactual',107200,'DATETIME','mosactual','2','MOS<br>Actual','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107230','btsinstallationcompleted',107230,'DATETIME','btsinstallationcompleted','2','BTS<br>Installation Completed','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107260','integratedplan',107260,'DATETIME','integratedplan','2','Integrated<br>Plan','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107290','integratedactual',107290,'DATETIME','integratedactual','2','Integrated<br>Actual','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107320','rfsplan',107320,'DATETIME','rfsplan','2','RFS<br>Plan','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107350','rfsactual',107350,'DATETIME','rfsactual','2','RFS<br>Actual','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107380','patactual',107380,'DATETIME','patactual','2','PAT<br>Actual','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107410','ssvactual',107410,'DATETIME','ssvactual','2','SSV<br>Actual','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107440','onairedactual',107440,'DATETIME','onairedactual','2','On-Aired<br>Actual','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107470','pacactual',107470,'DATETIME','pacactual','2','PAC<br>Actual','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107500','facactual',107500,'DATETIME','facactual','2','FAC<br>Actual','2','Telecom Works','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107530','permanentpowerapplied',107530,'DATETIME','permanentpowerapplied','2','Permanent Power Applied','2','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107560','jointinspectionsurveywithcoop',107560,'DATETIME','jointinspectionsurveywithcoop','2','Joint Inspection Survey with COOP','2','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107590','chargeletteracquired',107590,'DATETIME','chargeletteracquired','2','Charge Letter Acquired','2','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107620','powerpaymentrfpsubmitted',107620,'DATETIME','powerpaymentrfpsubmitted','2','Power Payment<br>RFP Submitted','2','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107650','powerpaymentrfpreleased',107650,'DATETIME','powerpaymentrfpreleased','2','Power Payment<br>RFP Released','2','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107680','lineconstruction',107680,'DATETIME','lineconstruction','2','Line<br>Construction','2','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107710','energizedplan',107710,'DATETIME','energizedplan','2','Energized<br>Plan','2','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107740','energizedactual',107740,'DATETIME','energizedactual','2','Energized<br>Actual','2','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107770','electricalpat',107770,'DATETIME','electricalpat','2','Electrical PAT','2','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107800','siteutilitycontractsubmitted',107800,'DATETIME','siteutilitycontractsubmitted','2','Site Utility Contract Submitted','2','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107830','meterserialnumber',107830,'DECIMAL(10,0)','meterserialnumber','1','Meter Serial Number','2','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107860','electriccooperative',107860,'VARCHAR(100)','electriccooperative','0','Electric Cooperative','1','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107890','powremarks',107890,'VARCHAR(200)','powremarks','0','Remarks','1','Permanent Power','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107920','ditophase',107920,'VARCHAR(100)','ditophase','0','DITO Phase','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107950','newpool',107950,'VARCHAR(100)','newpool','0','New POOL','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107980','uicprivatesite',107980,'VARCHAR(100)','uicprivatesite','0','UIC - Private Site','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108010','cmepriority',108010,'VARCHAR(100)','cmepriority','0','CME Priority','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108040','rfppriority',108040,'VARCHAR(100)','rfppriority','0','RFP Priority','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108070','finalprioritization',108070,'VARCHAR(100)','finalprioritization','0','FINAL PRIORITIZATION','1',null,'0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108100','extendt01',108100,'VARCHAR(100)','extendt01','0','extendt01','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108130','extendt02',108130,'VARCHAR(100)','extendt02','0','extendt02','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108160','extendt03',108160,'VARCHAR(100)','extendt03','0','extendt03','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108190','extendt04',108190,'VARCHAR(100)','extendt04','0','extendt04','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108220','extendt05',108220,'VARCHAR(100)','extendt05','0','extendt05','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108250','extendt06',108250,'VARCHAR(100)','extendt06','0','extendt06','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108280','extendt07',108280,'VARCHAR(100)','extendt07','0','extendt07','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108310','extendt08',108310,'VARCHAR(100)','extendt08','0','extendt08','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108340','extendt09',108340,'VARCHAR(100)','extendt09','0','extendt09','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108370','extendt10',108370,'VARCHAR(100)','extendt10','0','extendt10','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108400','extendt11',108400,'VARCHAR(100)','extendt11','0','extendt11','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108430','extendt12',108430,'VARCHAR(100)','extendt12','0','extendt12','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108460','extendt13',108460,'VARCHAR(100)','extendt13','0','extendt13','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108490','extendt14',108490,'VARCHAR(100)','extendt14','0','extendt14','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108520','extendt15',108520,'VARCHAR(100)','extendt15','0','extendt15','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108550','extendt16',108550,'VARCHAR(100)','extendt16','0','extendt16','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108580','extendt17',108580,'VARCHAR(100)','extendt17','0','extendt17','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108610','extendt18',108610,'VARCHAR(100)','extendt18','0','extendt18','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108640','extendt19',108640,'VARCHAR(100)','extendt19','0','extendt19','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108670','extendt20',108670,'VARCHAR(100)','extendt20','0','extendt20','1',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108700','extendi01',108700,'DECIMAL(10,0)','extendi01','1','extendi01','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108730','extendi02',108730,'DECIMAL(10,0)','extendi02','1','extendi02','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108760','extendi03',108760,'DECIMAL(10,0)','extendi03','1','extendi03','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108790','extendi04',108790,'DECIMAL(10,0)','extendi04','1','extendi04','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108820','extendi05',108820,'DECIMAL(10,0)','extendi05','1','extendi05','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108850','extendi06',108850,'DECIMAL(10,0)','extendi06','1','extendi06','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108880','extendi07',108880,'DECIMAL(10,0)','extendi07','1','extendi07','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108910','extendi08',108910,'DECIMAL(10,0)','extendi08','1','extendi08','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108940','extendi09',108940,'DECIMAL(10,0)','extendi09','1','extendi09','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108970','extendi10',108970,'DECIMAL(10,0)','extendi10','1','extendi10','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109000','extendi11',109000,'DECIMAL(10,0)','extendi11','1','extendi11','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109030','extendi12',109030,'DECIMAL(10,0)','extendi12','1','extendi12','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109060','extendi13',109060,'DECIMAL(10,0)','extendi13','1','extendi13','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109090','extendi14',109090,'DECIMAL(10,0)','extendi14','1','extendi14','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109120','extendi15',109120,'DECIMAL(10,0)','extendi15','1','extendi15','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109150','extendi16',109150,'DECIMAL(10,0)','extendi16','1','extendi16','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109180','extendi17',109180,'DECIMAL(10,0)','extendi17','1','extendi17','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109210','extendi18',109210,'DECIMAL(10,0)','extendi18','1','extendi18','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109240','extendi19',109240,'DECIMAL(10,0)','extendi19','1','extendi19','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109270','extendi20',109270,'DECIMAL(10,0)','extendi20','1','extendi20','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109300','extendd01',109300,'DATETIME','extendd01','2','extendd01','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109330','extendd02',109330,'DATETIME','extendd02','2','extendd02','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109360','extendd03',109360,'DATETIME','extendd03','2','extendd03','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109390','extendd04',109390,'DATETIME','extendd04','2','extendd04','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109420','extendd05',109420,'DATETIME','extendd05','2','extendd05','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109450','extendd06',109450,'DATETIME','extendd06','2','extendd06','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109480','extendd07',109480,'DATETIME','extendd07','2','extendd07','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109510','extendd08',109510,'DATETIME','extendd08','2','extendd08','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109540','extendd09',109540,'DATETIME','extendd09','2','extendd09','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109570','extendd10',109570,'DATETIME','extendd10','2','extendd10','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109600','extendd11',109600,'DATETIME','extendd11','2','extendd11','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109630','extendd12',109630,'DATETIME','extendd12','2','extendd12','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109660','extendd13',109660,'DATETIME','extendd13','2','extendd13','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109690','extendd14',109690,'DATETIME','extendd14','2','extendd14','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109720','extendd15',109720,'DATETIME','extendd15','2','extendd15','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109750','extendd16',109750,'DATETIME','extendd16','2','extendd16','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109780','extendd17',109780,'DATETIME','extendd17','2','extendd17','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109810','extendd18',109810,'DATETIME','extendd18','2','extendd18','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109840','extendd19',109840,'DATETIME','extendd19','2','extendd19','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109870','extendd20',109870,'DATETIME','extendd20','2','extendd20','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109900','extendd21',109900,'DATETIME','extendd21','2','extendd21','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109930','extendd22',109930,'DATETIME','extendd22','2','extendd22','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109960','extendd23',109960,'DATETIME','extendd23','2','extendd23','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109990','extendd24',109990,'DATETIME','extendd24','2','extendd24','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110020','extendd25',110020,'DATETIME','extendd25','2','extendd25','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110050','extendd26',110050,'DATETIME','extendd26','2','extendd26','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110080','extendd27',110080,'DATETIME','extendd27','2','extendd27','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110110','extendd28',110110,'DATETIME','extendd28','2','extendd28','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110140','extendd29',110140,'DATETIME','extendd29','2','extendd29','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110170','extendd30',110170,'DATETIME','extendd30','2','extendd30','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110200','extendd31',110200,'DATETIME','extendd31','2','extendd31','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110230','extendd32',110230,'DATETIME','extendd32','2','extendd32','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110260','extendd33',110260,'DATETIME','extendd33','2','extendd33','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110290','extendd34',110290,'DATETIME','extendd34','2','extendd34','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110320','extendd35',110320,'DATETIME','extendd35','2','extendd35','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110350','extendd36',110350,'DATETIME','extendd36','2','extendd36','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110380','extendd37',110380,'DATETIME','extendd37','2','extendd37','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110410','extendd38',110410,'DATETIME','extendd38','2','extendd38','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110440','extendd39',110440,'DATETIME','extendd39','2','extendd39','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110470','extendd40',110470,'DATETIME','extendd40','2','extendd40','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110500','extendd41',110500,'DATETIME','extendd41','2','extendd41','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110530','extendd42',110530,'DATETIME','extendd42','2','extendd42','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110560','extendd43',110560,'DATETIME','extendd43','2','extendd43','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110590','extendd44',110590,'DATETIME','extendd44','2','extendd44','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110620','extendd45',110620,'DATETIME','extendd45','2','extendd45','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110650','extendd46',110650,'DATETIME','extendd46','2','extendd46','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110680','extendd47',110680,'DATETIME','extendd47','2','extendd47','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110710','extendd48',110710,'DATETIME','extendd48','2','extendd48','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110740','extendd49',110740,'DATETIME','extendd49','2','extendd49','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110770','extendd50',110770,'DATETIME','extendd50','2','extendd50','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110800','extendn01',110800,'DECIMAL(8,6)','extendn01','4','extendn01','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110830','extendn02',110830,'DECIMAL(8,6)','extendn02','4','extendn02','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110860','extendn03',110860,'DECIMAL(8,6)','extendn03','4','extendn03','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110890','extendn04',110890,'DECIMAL(8,6)','extendn04','4','extendn04','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110920','extendn05',110920,'DECIMAL(8,6)','extendn05','4','extendn05','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110950','extendn06',110950,'DECIMAL(8,6)','extendn06','4','extendn06','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('110980','extendn07',110980,'DECIMAL(8,6)','extendn07','4','extendn07','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111010','extendn08',111010,'DECIMAL(8,6)','extendn08','4','extendn08','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111040','extendn09',111040,'DECIMAL(8,6)','extendn09','4','extendn09','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111070','extendn10',111070,'DECIMAL(8,6)','extendn10','4','extendn10','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111100','extendn11',111100,'DECIMAL(8,6)','extendn11','4','extendn11','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111130','extendn12',111130,'DECIMAL(8,6)','extendn12','4','extendn12','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111160','extendn13',111160,'DECIMAL(8,6)','extendn13','4','extendn13','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111190','extendn14',111190,'DECIMAL(8,6)','extendn14','4','extendn14','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111220','extendn15',111220,'DECIMAL(8,6)','extendn15','4','extendn15','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111250','extendn16',111250,'DECIMAL(8,6)','extendn16','4','extendn16','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111280','extendn17',111280,'DECIMAL(8,6)','extendn17','4','extendn17','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111310','extendn18',111310,'DECIMAL(8,6)','extendn18','4','extendn18','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111340','extendn19',111340,'DECIMAL(8,6)','extendn19','4','extendn19','2',null,'1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('111370','extendn20',111370,'DECIMAL(8,6)','extendn20','4','extendn20','2',null,'1','system',now(),'system',now(),'');