DELETE FROM yc_site_column;
INSERT INTO yc_site_column VALUES ('100000','physicalplansiteid',100000,'VARCHAR(64)','physicalplansiteid','0','Site ID','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100030','snnn',100030,'VARCHAR(100)','snnn','0','S/N','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100060','longitude',100060,'DECIMAL(10,7)','longitude','4','Longitude','2','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100090','latitude',100090,'DECIMAL(10,7)','latitude','4','Latitude','2','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100120','areatype',100120,'VARCHAR(100)','areatype','0','Area Type','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100150','sitetype',100150,'VARCHAR(100)','sitetype','0','Site Type','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100180','siteclassification',100180,'VARCHAR(100)','siteclassification','0','Site Classification','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100210','bands',100210,'VARCHAR(100)','bands','0','Bands','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100240','area',100240,'VARCHAR(100)','area','0','Area','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100270','region',100270,'VARCHAR(100)','region','0','Region','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100300','province',100300,'VARCHAR(100)','province','0','Province','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100330','city',100330,'VARCHAR(100)','city','0','City/Municipality','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100360','barangay',100360,'VARCHAR(100)','barangay','0','Barangay','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100390','height',100390,'DECIMAL(10,0)','height','1','Height(m)','2','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100420','towertype',100420,'VARCHAR(100)','towertype','0','Tower Type','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100450','cohoming',100450,'VARCHAR(100)','cohoming','0','CO Homing','1','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100480','distance',100480,'DECIMAL(19,10)','distance','4','Distance(km)','2','SITE INFORMATION (NOMINAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100481','mwantennaheight',100510,'VARCHAR(100)','mwantennaheight','0','MW antenna height','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100482','mwremark',100540,'VARCHAR(100)','mwremark','0','MW Remarks','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100483','mwsitetype',100570,'VARCHAR(100)','mwsitetype','0','MW site type','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100484','atnqty03m',100600,'VARCHAR(100)','atnqty03m','0','0.3m ATN Qty.','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100485','atnqty06m',100630,'VARCHAR(100)','atnqty06m','0','0.6m ATN Qty.','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100486','atnqty09m',100660,'VARCHAR(100)','atnqty09m','0','0.9m ATN Qty.','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100487','atnqty12m',100690,'VARCHAR(100)','atnqty12m','0','1.2m ATN Qty.','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100488','atnqty18m',100720,'VARCHAR(100)','atnqty18m','0','1.8m ATN Qty.','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100489','atnqty24m',100750,'VARCHAR(100)','atnqty24m','0','2.4m ATN Qty.','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100490','fibersite0229',100780,'VARCHAR(100)','fibersite0229','0','Fiber Site','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100491','transmission',100810,'VARCHAR(100)','transmission','0','Transmission','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100492','ranodcodf',100840,'VARCHAR(100)','ranodcodf','0','RAN ODC ODF','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100493','powersupplycabinet',100870,'VARCHAR(100)','powersupplycabinet','0','40U Power Supply cabinet','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100494','equipmentcabinet',100900,'VARCHAR(100)','equipmentcabinet','0','40U equipment cabinet','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100495','liibatterycabinet',100930,'VARCHAR(100)','liibatterycabinet','0','40U Li-I Battery Cabinet','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100496','liibattery',100960,'VARCHAR(100)','liibattery','0','150Ah Li-I Battery','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100497','rectifier',100990,'VARCHAR(100)','rectifier','0','50A Rectifier','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100498','dcdu',101020,'VARCHAR(100)','dcdu','0','DCDU','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100499','fms',101050,'VARCHAR(100)','fms','0','FMS','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100500','cabinetqty',101080,'VARCHAR(100)','cabinetqty','0','Cabinet qty','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100501','backuptime',101110,'VARCHAR(100)','backuptime','0','Backup time','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100502','acpowercapacity',101140,'VARCHAR(100)','acpowercapacity','0','AC Power Capacity(kW)','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100503','transformer',101170,'VARCHAR(100)','transformer','0','Transformer（KVA)','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100504','altitude',101200,'VARCHAR(100)','altitude','0','Altitude','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100505','buildingheightrt',101230,'VARCHAR(100)','buildingheightrt','0','Building Height(RT)','1','SITE CONFIGURATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100510','ditopriority',101260,'VARCHAR(100)','ditopriority','0','DITO Priority','1','PROJECT PRIORITIZATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100515','priorstatus',101290,'VARCHAR(100)','priorstatus','0','Status','1','PROJECT PRIORITIZATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100520','citiespriority',101320,'VARCHAR(100)','citiespriority','0','6 Cities Priority','1','PROJECT PRIORITIZATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100540','prioritybaseline',101350,'VARCHAR(100)','prioritybaseline','0','Priority(Baseline)','1','PROJECT PRIORITIZATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100570','priority2020v2',101380,'VARCHAR(100)','priority2020v2','0','Priority(2020v2)','1','PROJECT PRIORITIZATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100600','rfppriority',101410,'VARCHAR(100)','rfppriority','0','RFP Priority','1','PROJECT PRIORITIZATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100630','friendlysite',101440,'VARCHAR(100)','friendlysite','0','Cooperation Site','1','PROJECT PRIORITIZATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100660','uicprivatesite',101470,'VARCHAR(100)','uicprivatesite','0','UIC - Private Site','1','PROJECT PRIORITIZATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100690','saqclustering',101500,'VARCHAR(100)','saqclustering','0','SAQ Clustering','0','PROJECT PRIORITIZATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100720','saqvendor',101530,'VARCHAR(100)','saqvendor','0','SAQ Vendor','0','VENDOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100750','saqponumber',101560,'VARCHAR(100)','saqponumber','0','SAQ PO Number','1','VENDOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100780','tssdddvendor',101590,'VARCHAR(100)','tssdddvendor','0','TSS/DDD Vendor','0','VENDOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100810','tssdddponumber',101620,'VARCHAR(100)','tssdddponumber','0','TSS/DDD PO Number','1','VENDOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100840','cmevendor',101650,'VARCHAR(100)','cmevendor','0','CME Vendor','0','VENDOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100870','cmeponumber',101680,'VARCHAR(100)','cmeponumber','0','CME PO Number','1','VENDOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100875','pwrvendor',101710,'VARCHAR(100)','pwrvendor','0','PWR Vendor','1','VENDOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100880','pwrponumber',101740,'VARCHAR(100)','pwrponumber','0','PWR PO Number','1','VENDOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100900','twvendor',101770,'VARCHAR(100)','twvendor','0','TI Vendor','0','VENDOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100930','twponumber',101800,'VARCHAR(100)','twponumber','0','TI PO Number','1','VENDOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100960','sarfissued',101830,'DATETIME','sarfissued','2','SARF Issued','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('100990','surveydoneplan',101860,'DATETIME','surveydoneplan','2','Survey Done Plan','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101020','surverydone',101890,'DATETIME','surverydone','2','Survey Done','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101050','sarsubmittedplan',101920,'DATETIME','sarsubmittedplan','2','SAR Submitted Plan','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101080','sarsubmittedoptiona',101950,'DATETIME','sarsubmittedoptiona','2','SAR Submitted Option A','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101110','sarsubmittedoptionb',101980,'DATETIME','sarsubmittedoptionb','2','SAR Submitted Option B','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101140','sarsubmittedoptionc',102010,'DATETIME','sarsubmittedoptionc','2','SAR Submitted Option C','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101170','sarsubmittedoptiond',102040,'DATETIME','sarsubmittedoptiond','2','SAR Submitted Option D','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101175','sarsubmittedoptione',102070,'DATETIME','sarsubmittedoptione','2','SAR Submitted Option E','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101180','sarsubmittedoptionf',102100,'DATETIME','sarsubmittedoptionf','2','SAR Submitted Option F','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101200','sarsubmitted',102130,'DATETIME','sarsubmitted','2','SAR Submitted','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101230','sarapprovedplan',102160,'DATETIME','sarapprovedplan','2','SAR Approved Plan','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101260','sarapprovedoptiona',102190,'DATETIME','sarapprovedoptiona','2','SAR Approved Option A','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101290','sarapprovedoptionb',102220,'DATETIME','sarapprovedoptionb','2','SAR Approved Option B','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101320','sarapprovedoptionc',102250,'DATETIME','sarapprovedoptionc','2','SAR Approved Option C','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101350','sarapprovedoptiond',102280,'DATETIME','sarapprovedoptiond','2','SAR Approved Option D','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101355','sarapprovedoptione',102310,'DATETIME','sarapprovedoptione','2','SAR Approved Option E','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101360','sarapprovedoptionf',102340,'DATETIME','sarapprovedoptionf','2','SAR Approved Option F','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101380','sarapproved',102370,'DATETIME','sarapproved','2','SAR Approved','2','SITE HUNTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101385','mocsignedplan',102400,'DATETIME','mocsignedplan','2','MOC Signed Plan','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101410','mocsignedoptiona',102430,'DATETIME','mocsignedoptiona','2','MOC Signed Option A','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101440','mocsignedoptionb',102460,'DATETIME','mocsignedoptionb','2','MOC Signed Option B','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101470','mocsignedoptionc',102490,'DATETIME','mocsignedoptionc','2','MOC Signed Option C','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101500','mocsignedoptiond',102520,'DATETIME','mocsignedoptiond','2','MOC Signed Option D','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101505','mocsignedoptione',102550,'DATETIME','mocsignedoptione','2','MOC Signed Option E','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101510','mocsignedoptionf',102580,'DATETIME','mocsignedoptionf','2','MOC Signed Option F','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101530','mocsigned',102610,'DATETIME','mocsigned','2','MOC Signed','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101560','mocsubmitted',102640,'DATETIME','mocsubmitted','2','MOC Submitted','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101590','mocapprovedplan',102670,'DATETIME','mocapprovedplan','2','MOC Approved Plan','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101620','mocapproved',102700,'DATETIME','mocapproved','2','MOC Approved','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101650','nrafsubmitted',102730,'DATETIME','nrafsubmitted','2','NRAF Submitted','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101660','nrafapprovedplan',102760,'DATETIME','nrafapprovedplan','2','NRAF Approved Plan','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101680','nrafapproved',102790,'DATETIME','nrafapproved','2','NRAF Approved','2','LEASE NEGOTIATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101710','approvedoption',102820,'VARCHAR(100)','approvedoption','0','Approved Option','1','SITE INFORMATION (ACTUAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101980','sisitetype',102850,'VARCHAR(100)','sisitetype','0','SI Site Type','1','SITE INFORMATION (ACTUAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101920','silongitude',102880,'DECIMAL(10,7)','silongitude','4','SI Longitude','2','SITE INFORMATION (ACTUAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101950','silatitude',102910,'DECIMAL(10,7)','silatitude','4','SI Latitude','2','SITE INFORMATION (ACTUAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101770','streetbuilding',102940,'VARCHAR(100)','streetbuilding','0','Street/Building','1','SITE INFORMATION (ACTUAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101800','actbarangay',102970,'VARCHAR(100)','actbarangay','0','SI Barangay','1','SITE INFORMATION (ACTUAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101830','citymunicipality',103000,'VARCHAR(100)','citymunicipality','0','SI City/Municipality','1','SITE INFORMATION (ACTUAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101860','siprovince',103030,'VARCHAR(100)','siprovince','0','SI Province','1','SITE INFORMATION (ACTUAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101890','completesiteaddress',103060,'VARCHAR(255)','completesiteaddress','0','Complete Site Address','1','SITE INFORMATION (ACTUAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('101740','lessorname',103090,'VARCHAR(100)','lessorname','0','Lessor Name','1','LESSOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103150','lessorcontact',103120,'VARCHAR(100)','lessorcontact','0','Lessor Contact','1','LESSOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103180','lessoraddress',103150,'VARCHAR(100)','lessoraddress','0','Lessor Address','1','LESSOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103185','typeoflessor',103180,'VARCHAR(100)','typeoflessor','0','Type of Lessor','1','LESSOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103030','tinnn',103210,'VARCHAR(100)','tinnn','0','TIN','1','LESSOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103060','bankaccountname',103240,'VARCHAR(100)','bankaccountname','0','Bank Account Name','1','LESSOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103090','banknamebranch',103270,'VARCHAR(100)','banknamebranch','0','Bank Name & Branch','1','LESSOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103120','bankaccountnumber',103300,'VARCHAR(100)','bankaccountnumber','0','Bank Account Number','1','LESSOR INFORMATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102040','periodoflease',103330,'VARCHAR(100)','periodoflease','0','Period of Lease','1','COMMERCIAL TERMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102070','monthlyrent',103360,'VARCHAR(100)','monthlyrent','0','Monthly Rent','1','COMMERCIAL TERMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102100','taxprovision',103390,'VARCHAR(100)','taxprovision','0','Tax Provision','1','COMMERCIAL TERMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102130','vatamount',103420,'VARCHAR(100)','vatamount','0','VAT Amount(12%)','1','COMMERCIAL TERMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102160','whtamount',103450,'VARCHAR(100)','whtamount','0','WHT Amount(5%)','1','COMMERCIAL TERMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102190','escalationrate',103480,'VARCHAR(100)','escalationrate','0','Escalation Rate','1','COMMERCIAL TERMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102220','advancerental',103510,'VARCHAR(100)','advancerental','0','Advance Rental','1','COMMERCIAL TERMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102250','securitydeposit',103540,'VARCHAR(100)','securitydeposit','0','Security Deposit','1','COMMERCIAL TERMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102310','modeofpayment',103570,'VARCHAR(100)','modeofpayment','0','Mode of Payment','1','COMMERCIAL TERMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102340','leasearea',103600,'VARCHAR(100)','leasearea','0','Lease Area','1','COMMERCIAL TERMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102370','neighborsconsent',103630,'DATETIME','neighborsconsent','2','Neighbors Consent','2','SOCIAL ACCEPTABILITY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102400','noneighborscertificate',103660,'DATETIME','noneighborscertificate','2','No Neighbors Certificate','2','SOCIAL ACCEPTABILITY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102430','nameofsubdivisionhoa',103690,'DATETIME','nameofsubdivisionhoa','2','Name of Subdivision/HOA','2','SOCIAL ACCEPTABILITY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102460','nameofhoapresident',103720,'DATETIME','nameofhoapresident','2','Name of HOA President','2','SOCIAL ACCEPTABILITY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102490','hoapresidentcontactno',103750,'DATETIME','hoapresidentcontactno','2','HOA President Contact No.','2','SOCIAL ACCEPTABILITY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102520','hoaclearancesecured',103780,'DATETIME','hoaclearancesecured','2','HOA Clearance Secured','2','SOCIAL ACCEPTABILITY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102550','brappliedplan',103810,'DATETIME','brappliedplan','2','BR Applied Plan','2','BARANGAY PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102580','brapplied',103840,'DATETIME','brapplied','2','BR Applied','2','BARANGAY PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102610','bcsecured',103870,'DATETIME','bcsecured','2','BC Secured','2','BARANGAY PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102640','bcsecuredplan',103900,'DATETIME','bcsecuredplan','2','BR Secured Plan','2','BARANGAY PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102670','brsecured',103930,'DATETIME','brsecured','2','BR Secured','2','BARANGAY PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102700','propdocsstartedplan',103960,'DATETIME','propdocsstartedplan','2','Property Documents Plan','2','PROPERTY DOCUMENTS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102730','taxdeclarationsecured',103990,'DATETIME','taxdeclarationsecured','2','Tax Declaration Secured','2','PROPERTY DOCUMENTS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102760','taxclearancesecured',104020,'DATETIME','taxclearancesecured','2','Tax Clearance Secured','2','PROPERTY DOCUMENTS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102790','tctsecured',104050,'DATETIME','tctsecured','2','TCT Secured','2','PROPERTY DOCUMENTS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102820','conceptualdrawingsigned',104080,'DATETIME','conceptualdrawingsigned','2','Conceptual Drawing Signed','2','PROPERTY DOCUMENTS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102850','lessorinformationsheet',104110,'DATETIME','lessorinformationsheet','2','Lessor Info Sheet Signed','2','PROPERTY DOCUMENTS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102910','segregationplansigned',104140,'DATETIME','segregationplansigned','2','Lot Segregation Plan Signed','2','PROPERTY DOCUMENTS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102940','lessorid',104170,'VARCHAR(100)','lessorid','0','Lessor ID','1','PROPERTY DOCUMENTS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103210','landclassification',104200,'VARCHAR(100)','landclassification','0','Land Classification','1','PROPERTY DOCUMENTS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103240','propdocsdoneplan',104230,'DATETIME','propdocsdoneplan','2','Property Docs Done Plan','2','PROPERTY DOCUMENTS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103270','propertydocscompleted',104260,'DATETIME','propertydocscompleted','2','Property Docs Completed','2','PROPERTY DOCUMENTS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102970','draftcolplan',104290,'DATETIME','draftcolplan','2','Draft COL Plan','2','SITE LEASE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103000','draftcolsigned',104320,'DATETIME','draftcolsigned','2','Draft COL Signed by Lessor','2','SITE LEASE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104680','leasepackagesubmitted',104350,'DATETIME','leasepackagesubmitted','2','Lease Package Submitted','2','SITE LEASE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103280','colreviewedbylegal',104380,'DATETIME','colreviewedbylegal','2','COL Reviewed by Legal','2','SITE LEASE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103300','colapprovedbyLegal',104410,'DATETIME','colapprovedbyLegal','2','COL Approved by Legal','2','SITE LEASE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103330','cspfsubmitted',104440,'DATETIME','cspfsubmitted','2','CSPF Submitted','2','SITE LEASE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103360','cspfapproved',104470,'DATETIME','cspfapproved','2','CSPF Approved','2','SITE LEASE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103390','colsignedbydito',104500,'DATETIME','colsignedbydito','2','COL Signed by DITO','2','SITE LEASE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103420','colsignedbylessor',104530,'DATETIME','colsignedbylessor','2','COL Signed by Lessor','2','SITE LEASE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103450','colsignedplan',104560,'DATETIME','colsignedplan','2','COL Signed Plan','2','SITE LEASE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103480','colsignedbybothparties',104590,'DATETIME','colsignedbybothparties','2','COL Signed by Both Parties','2','SITE LEASE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103510','rfpsubmitted',104620,'DATETIME','rfpsubmitted','2','RFP Submitted','2','REQUEST FOR PAYMENT','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103540','rfpapproved',104650,'DATETIME','rfpapproved','2','RFP Approved','2','REQUEST FOR PAYMENT','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103570','rentalpaidplan',104680,'DATETIME','rentalpaidplan','2','Rental Paid Plan','2','REQUEST FOR PAYMENT','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103600','chequereleased',104710,'DATETIME','chequereleased','2','Cheque Released','2','REQUEST FOR PAYMENT','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103630','chequereceivedbylessorr',104740,'DATETIME','chequereceivedbylessorr','2','Cheque Received by Lessor','2','REQUEST FOR PAYMENT','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103660','arorsubmittedtodito',104770,'DATETIME','arorsubmittedtodito','2','AR Submitted','2','REQUEST FOR PAYMENT','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103661','ndrfpsubmitted',104800,'DATETIME','ndrfpsubmitted','2','2nd RFP Submitted','2','REQUEST FOR PAYMENT','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103662','ndrfpapproved',104830,'DATETIME','ndrfpapproved','2','2nd RFP Approved','2','REQUEST FOR PAYMENT','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103663','ndchequereleased',104860,'DATETIME','ndchequereleased','2','2nd Cheque Released ','2','REQUEST FOR PAYMENT','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103664','ndchequereceivedbylessor',104890,'DATETIME','ndchequereceivedbylessor','2','2nd Cheque Received by Lessor','2','REQUEST FOR PAYMENT','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103665','ndarsubmitted',104920,'DATETIME','ndarsubmitted','2','2nd AR Submitted','2','REQUEST FOR PAYMENT','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104740','sbtsidoneplan',104950,'DATETIME','sbtsidoneplan','2','SBT/SI Done Plan','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104770','sbtsidone',104980,'DATETIME','sbtsidone','2','SBT/SI Done','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104800','sbtsireportplan',105010,'DATETIME','sbtsireportplan','2','SBT/SI Report Plan','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104805','sbtsipresubmitted',105040,'DATETIME','sbtsipresubmitted','2','SBT/SI Pre-Report Submitted','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104830','sbtsireportsubmitted',105070,'DATETIME','sbtsireportsubmitted','2','SBT/SI Report Submitted','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104860','sbtsireportapproved',105100,'DATETIME','sbtsireportapproved','2','SBT/SI Report Approved','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104890','tssdoneplan',105130,'DATETIME','tssdoneplan','2','TSS Done Plan','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104920','tssdone',105160,'DATETIME','tssdone','2','TSS Done','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104950','tssrsubmittedplan',105190,'DATETIME','tssrsubmittedplan','2','TSSR Submitted Plan','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104955','pretssrsubmitted',105220,'DATETIME','pretssrsubmitted','2','Pre-TSSR Submitted','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104980','tssrsubmitted',105250,'DATETIME','tssrsubmitted','2','TSSR Submitted','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104985','mwpretssrsubmitted',105280,'DATETIME','mwpretssrsubmitted','2','MW Pre-TSSR Submitted','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105010','mwtssrsubmitted',105310,'DATETIME','mwtssrsubmitted','2','MW TSSR Submitted','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105040','tssrapproved',105340,'DATETIME','tssrapproved','2','TSSR Approved','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105045','sbtsitssrapproved',105370,'DATETIME','sbtsitssrapproved','2','SBT/SI Report & TSSR Approved','2','GEOLOGICAL & TECHNICAL SITE SURVEY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103720','nationalpermitplan',105400,'DATETIME','nationalpermitplan','2','National Permits Plan','2','NATIONAL PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103750','cncapplied',105430,'DATETIME','cncapplied','2','CNC Applied','2','NATIONAL PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103780','cncacquired',105460,'DATETIME','cncacquired','2','CNC Acquired','2','NATIONAL PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103810','dohapplied',105490,'DATETIME','dohapplied','2','DOH Applied','2','NATIONAL PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103840','dohacquired',105520,'DATETIME','dohacquired','2','DOH Acquired','2','NATIONAL PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103870','caapapplied',105550,'DATETIME','caapapplied','2','CAAP Applied','2','NATIONAL PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103900','caapacquired',105580,'DATETIME','caapacquired','2','CAAP Acquired','2','NATIONAL PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103930','natlcompletedplan',105610,'DATETIME','natlcompletedplan','2','National Completed Plan','2','NATIONAL PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103960','lgupermitplan',105640,'DATETIME','lgupermitplan','2','LGU Permits Plan','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('103990','sbspapplied',105670,'DATETIME','sbspapplied','2','SB/SP Applied','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104020','sbspacquired',105700,'DATETIME','sbspacquired','2','SB/SP Acquired','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104080','lczoningapplied',105730,'DATETIME','lczoningapplied','2','LC/Zoning Applied','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104110','zoningacquired',105760,'DATETIME','zoningacquired','2','Zoning Acquired','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104140','locationalacquired',105790,'DATETIME','locationalacquired','2','Locational Acquired','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104170','bpapplied',105820,'DATETIME','bpapplied','2','Building Permit Applied','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104230','electricalpermitsecured',105850,'DATETIME','electricalpermitsecured','2','Electrical Permit Secured','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104260','mechanicalpermitsecured',105880,'DATETIME','mechanicalpermitsecured','2','Mechanical Permit Secured','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104290','electronicspermitsecured',105910,'DATETIME','electronicspermitsecured','2','Electronics Permit Secured','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104320','fencingpermitsecured',105940,'DATETIME','fencingpermitsecured','2','Fencing Permit Secured','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104350','sanitarypermitsecured',105970,'DATETIME','sanitarypermitsecured','2','Sanitary Permit Secured','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104380','fsecacquired',106000,'DATETIME','fsecacquired','2','FSEC Acquired','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104200','bpsecured',106030,'DATETIME','bpsecured','2','Building Permit Secured','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104410','lgucompletedplan',106060,'DATETIME','lgucompletedplan','2','LGU Completed Plan','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104440','rtbplan',106090,'DATETIME','rtbplan','2','RTB Plan','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104441','rtb1',106120,'DATETIME','rtb1','2','RTB 1','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104470','rtb',106150,'DATETIME','rtb','2','RTB 2','2','PRE-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105070','dddsubmittedplan',106180,'DATETIME','dddsubmittedplan','2','DDD Submitted Plan','2','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105100','tedddsubmitted',106210,'DATETIME','tedddsubmitted','2','Pre-DDD Submitted','2','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105130','tedddapproved',106240,'DATETIME','tedddapproved','2','DDD Approved by HX','2','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105160','cwdddsubmitted',106270,'DATETIME','cwdddsubmitted','2','DDD Submitted','2','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105190','dddapprovedplan',106300,'DATETIME','dddapprovedplan','2','DDD Approved Plan','2','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105220','cwdddapproved',106330,'DATETIME','cwdddapproved','2','DDD Approved','2','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105225','mwpredddsubmitted',106360,'DATETIME','mwpredddsubmitted','2','MW Pre-DDD Submitted','2','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105230','mwdddapprovedbyhx',106390,'DATETIME','mwdddapprovedbyhx','2','MW DDD Approved by HX','2','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105250','mwdddsubmitted',106420,'DATETIME','mwdddsubmitted','2','MW DDD Submitted','2','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105280','mwdddapproved',106450,'DATETIME','mwdddapproved','2','MW DDD Approved','2','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105310','sttowertype',106480,'VARCHAR(100)','sttowertype','0','Tower Type & Height','1','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105320','dddapprovedtype',106510,'VARCHAR(100)','dddapprovedtype','0','DDD approved type','1','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105370','towerdeliveryonsiteplan',106540,'DATETIME','towerdeliveryonsiteplan','2','Tower Delivered on Site Plan','2','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105400','towerdeliveryonsite',106570,'DATETIME','towerdeliveryonsite','2','Tower Delivered on Site','2','TOWER DESIGN & DELIVERY','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105401','skomplan',106600,'DATETIME','skomplan','2','SKOM Plan','2','CONSTRUCTION PRELIMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105430','skomactual',106630,'DATETIME','skomactual','2','SKOM','2','CONSTRUCTION PRELIMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105460','mobilizationplan',106660,'DATETIME','mobilizationplan','2','Mobilization Plan','2','CONSTRUCTION PRELIMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105490','mobilizationstarted',106690,'DATETIME','mobilizationstarted','2','Mobilization','2','CONSTRUCTION PRELIMS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105520','excavationplan',106720,'DATETIME','excavationplan','2','Excavation / RT Clean Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105550','excavationsrc',106750,'DATETIME','excavationsrc','2','Excavation / RT Clean Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105551','excavationrtcleandone',106780,'DATETIME','excavationrtcleandone','2','Excavation / RT Clean Done','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105552','foundationpitrepairplan',106810,'DATETIME','foundationpitrepairplan','2','Foundation Pit Repair Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105553','foundationpitrepairstarted',106840,'DATETIME','foundationpitrepairstarted','2','Foundation Pit Repair Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105554','foundationpitrepairdone',106870,'DATETIME','foundationpitrepairdone','2','Foundation Pit Repair Done','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105555','rebarpreparationplan',106900,'DATETIME','rebarpreparationplan','2','Rebar Preparation Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105556','rebarpreparationstarted',106930,'DATETIME','rebarpreparationstarted','2','Rebar Preparation Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105557','rebarpreparationdone',106960,'DATETIME','rebarpreparationdone','2','Rebar Preparation Done','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105558','formworkspreparationplan',106990,'DATETIME','formworkspreparationplan','2','Formworks Preparation Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105559','formworkspreparationstarted',107020,'DATETIME','formworkspreparationstarted','2','Formworks Preparation Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105560','formworkspreparationdone',107050,'DATETIME','formworkspreparationdone','2','Formworks Preparation Done','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105561','leanconcreteplan',107080,'DATETIME','leanconcreteplan','2','Lean Concrete Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105562','leanconcretestarted',107110,'DATETIME','leanconcretestarted','2','Lean Concrete Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105580','leanconcretecompletion',107140,'DATETIME','leanconcretecompletion','2','Lean Concrete Completed','2','CONSTRUCTION WORKS / TOWER FOUNDATION (PREPARATION)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105610','rebarsplan',107170,'DATETIME','rebarsplan','2','Footing Rebar Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105611','footingrebarstarted',107200,'DATETIME','footingrebarstarted','2','Footing Rebar Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105640','rebarformworkre',107230,'DATETIME','rebarformworkre','2','Footing Rebar Done','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105641','footingformworksplan',107260,'DATETIME','footingformworksplan','2','Footing Formworks Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105642','footingformworksstarted',107290,'DATETIME','footingformworksstarted','2','Footing Formworks Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105643','footingformworksdone',107320,'DATETIME','footingformworksdone','2','Footing Formworks Done','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105644','footingconcretepourplan',107350,'DATETIME','footingconcretepourplan','2','Footing Concrete Pouring Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105645','footingconcretepourstarted',107380,'DATETIME','footingconcretepourstarted','2','Footing Concrete Pouring Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105700','concretepouringcompleted',107410,'DATETIME','concretepouringcompleted','2','Footing Concrete Pouring Completed','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105701','footingconcurplan',107440,'DATETIME','footingconcurplan','2','Footing Concret Curing Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105702','footingconecurstarted',107470,'DATETIME','footingconecurstarted','2','Footing Concrete Curing Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105703','footingconecurcompleted',107500,'DATETIME','footingconecurcompleted','2','Footing Concrete Curing Completed','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105704','footingfwremovalplan',107530,'DATETIME','footingfwremovalplan','2','Footing Formworks Removal Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105705','footingfwremovalstarted',107560,'DATETIME','footingfwremovalstarted','2','Footing Formworks Removal Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105706','footingfwremovaldone',107590,'DATETIME','footingfwremovaldone','2','Footing Formworks Removal Done','2','CONSTRUCTION WORKS / TOWER FOUNDATION (FOOTING)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105707','columnrebarplan',107620,'DATETIME','columnrebarplan','2','Column Rebar Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105708','columnrebarstarted',107650,'DATETIME','columnrebarstarted','2','Column Rebar Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105709','columnrebardone',107680,'DATETIME','columnrebardone','2','Column Rebar Done','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105710','anchorboltsinstaplan',107710,'DATETIME','anchorboltsinstaplan','2','Anchor Bolts Installation Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105711','anchorboltsinstastarted',107740,'DATETIME','anchorboltsinstastarted','2','Anchor Bolts Installation Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105712','anchorboltsinstadone',107770,'DATETIME','anchorboltsinstadone','2','Anchor Bolts Installation Done','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105713','columnfwplan',107800,'DATETIME','columnfwplan','2','Column Formworks Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105714','columnfwstarted',107830,'DATETIME','columnfwstarted','2','Column Formworks Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105715','columnfwdone',107860,'DATETIME','columnfwdone','2','Column Formworks Done','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105716','pedestalconepouplan',107890,'DATETIME','pedestalconepouplan','2','Pedestal Concrete Pouring Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105717','pedestalconepoustarted',107920,'DATETIME','pedestalconepoustarted','2','Pedestal Concrete Pouring Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105718','pedestalconepoucompleted',107950,'DATETIME','pedestalconepoucompleted','2','Pedestal Concrete Pouring Completed','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105719','columnfwremovalplan',107980,'DATETIME','columnfwremovalplan','2','Column Formworks Removal Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105720','columnfwremoval',108010,'DATETIME','columnfwremoval','2','Column Formworks Removal','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105730','backfillingplan',108040,'DATETIME','backfillingplan','2','Back Filling Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105731','backfillingstarted',108070,'DATETIME','backfillingstarted','2','Back Filling Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105760','concretecuringbackfilling',108100,'DATETIME','concretecuringbackfilling','2','Back Filling Completed','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105761','pedesconcurplan',108130,'DATETIME','pedesconcurplan','2','Pedestal Concrete Curing Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105762','pedesconcurstarted',108160,'DATETIME','pedesconcurstarted','2','Pedestal Concrete Curing Started','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105763','pedesconcurcompleted',108190,'DATETIME','pedesconcurcompleted','2','Pedestal Concrete Curing Completed','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105764','sitecleplan',108220,'DATETIME','sitecleplan','2','Site Clearing Plan','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105765','siteclecompleted',108250,'DATETIME','siteclecompleted','2','Site Clearing Completed','2','CONSTRUCTION WORKS / TOWER FOUNDATION (COLUMN/PEDESTAL)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105766','towererestartedplan',108280,'DATETIME','towererestartedplan','2','Tower Erection Started Plan','2','TOWER ERECTION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105790','towererectionstarted',108310,'DATETIME','towererectionstarted','2','Tower Erection Started','2','TOWER ERECTION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105820','towererectionplan',108340,'DATETIME','towererectionplan','2','Tower Erection Completed Plan','2','TOWER ERECTION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105850','towererectioncompleted',108370,'DATETIME','towererectioncompleted','2','Tower Erection Completed','2','TOWER ERECTION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105851','fencebasicsplan',108400,'DATETIME','fencebasicsplan','2','Fence Basics Plan','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105852','fencebasicsstarted',108430,'DATETIME','fencebasicsstarted','2','Fence Basics Started','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105853','fencebasicscompleted',108460,'DATETIME','fencebasicscompleted','2','Fence Basics Completed','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105854','fencemasplan',108490,'DATETIME','fencemasplan','2','Fence Masonry Plan','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105855','fencemasstarted',108520,'DATETIME','fencemasstarted','2','Fence Masonry Started','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105856','fencemascompleted',108550,'DATETIME','fencemascompleted','2','Fence Masonry Completed','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105857','fencepaintplan',108580,'DATETIME','fencepaintplan','2','Fence Painting Plan','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105858','fencepaintstarted',108610,'DATETIME','fencepaintstarted','2','Fence Painting Started','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105859','fencepaintcompleted',108640,'DATETIME','fencepaintcompleted','2','Fence Painting Completed','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105860','gateinstplan',108670,'DATETIME','gateinstplan','2','Gate Installation Plan','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105861','gateinststarted',108700,'DATETIME','gateinststarted','2','Gate Installation Started','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105862','gateinstdone',108730,'DATETIME','gateinstdone','2','Gate Installation Done','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105863','sitedevplan',108760,'DATETIME','sitedevplan','2','Site Development Plan','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106000','sitedevworkscompleted',108790,'DATETIME','sitedevworkscompleted','2','Site Dev Works Completed','2','SITE DEVELOPMENT WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106001','odupadplan',108820,'DATETIME','odupadplan','2','ODU Pad Plan','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105880','odupadstarted',108850,'DATETIME','odupadstarted','2','ODU Pad Started','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105910','odupadcompleted',108880,'DATETIME','odupadcompleted','2','ODU Pad Completed','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105940','electricalgroundingplan',108910,'DATETIME','electricalgroundingplan','2','Electrical & Grounding Installation Plan','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105941','electricalgroinstallstart',108940,'DATETIME','electricalgroinstallstart','2','Electrical & Grounding Installation Started','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105970','electricalgroundinginstall',108970,'DATETIME','electricalgroundinginstall','2','Electrical & Grounding Installation Done','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105971','nameofneighbor',109000,'DATETIME','nameofneighbor','2','Name of Neighbor','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105972','tpasubmittedtodito',109030,'DATETIME','tpasubmittedtodito','2','TPA Submitted to DITO','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('105973','tpasignedbydito',109060,'DATETIME','tpasignedbydito','2','TPA Signed by DITO','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('102880','tpcaspca',109090,'DATETIME','tpcaspca','2','Tempo Power with Neighbor','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107140','electriccooperative',109120,'VARCHAR(100)','electriccooperative','0','Electric Cooperative','1','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107141','tpcsubmittedtodito',109150,'DATETIME','tpcsubmittedtodito','2','TPC Submitted to DITO','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107142','tpcsignedbydito',109180,'DATETIME','tpcsignedbydito','2','TPC Signed by DITO','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107143','tempopowerwithcoop',109210,'DATETIME','tempopowerwithcoop','2','Tempo Power with COOP','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107144','temporfpsubmitted',109240,'DATETIME','temporfpsubmitted','2','Tempo RFP Submitted','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107145','temporfpapproved',109270,'DATETIME','temporfpapproved','2','Tempo RFP Approved','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107146','temporfpreleased',109300,'DATETIME','temporfpreleased','2','Tempo RFP Released','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106030','tempopowerplan',109330,'DATETIME','tempopowerplan','2','Tempo Power Plan','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106060','tempopowerconnected',109360,'DATETIME','tempopowerconnected','2','Tempo Power Connected','2','ELECTRICAL & GROUNDING WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106090','rftiplan',109390,'DATETIME','rftiplan','2','RFTI Plan','2','READY FOR TELECOM INSTALLATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106120','rfti',109420,'DATETIME','rfti','2','RFTI','2','READY FOR TELECOM INSTALLATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106150','cwprepat',109450,'DATETIME','cwprepat','2','CW Pre-PAT','2','READY FOR TELECOM INSTALLATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106180','cwpatplan',109480,'DATETIME','cwpatplan','2','CW PAT Plan','2','READY FOR TELECOM INSTALLATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106210','cwpatpassed',109510,'DATETIME','cwpatpassed','2','CW PAT Passed','2','READY FOR TELECOM INSTALLATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104480','postconpermitsplan',109540,'DATETIME','postconpermitsplan','2','Post-Con Permits Plan','2','POST-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104500','fsicapplied',109570,'DATETIME','fsicapplied','2','FSIC Applied','2','POST-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104530','fsicacquired',109600,'DATETIME','fsicacquired','2','FSIC Acquired','2','POST-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104560','cfeiapplied',109630,'DATETIME','cfeiapplied','2','CFEI Applied','2','POST-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104590','cfeiacquired',109660,'DATETIME','cfeiacquired','2','CFEI Acquired','2','POST-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104620','opapplied',109690,'DATETIME','opapplied','2','Occupancy Permit Applied','2','POST-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104650','opsecured',109720,'DATETIME','opsecured','2','Occupancy Permit Secured','2','POST-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104660','postconcompletedplan',109750,'DATETIME','postconcompletedplan','2','Post-Con Completed Plan','2','POST-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104661','saqfoldersubmitted',109780,'DATETIME','saqfoldersubmitted','2','SAQ Site Folder Submitted','2','POST-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('104662','saqfolderapproved',109810,'DATETIME','saqfolderapproved','2','SAQ Site Folder Approved','2','POST-CONSTRUCTION PERMITTING','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106780','permanentpowerplan',109840,'DATETIME','permanentpowerplan','2','Permanent Power Plan','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106810','permanentpowerapplied',109870,'DATETIME','permanentpowerapplied','2','Permanent Power Applied','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106840','jointinspectionswc',109900,'DATETIME','jointinspectionswc','2','Joint Survey with COOP','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106870','chargeletteracquired',109930,'DATETIME','chargeletteracquired','2','Charge Letter Acquired','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106940','servicecontractsubmitted',109960,'DATETIME','servicecontractsubmitted','2','Service Contract Submitted','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106941','servicecontractsigned',109990,'DATETIME','servicecontractsigned','2','Service Contract Signed','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106900','powerpaymentrfpsub',110020,'DATETIME','powerpaymentrfpsub','2','Power RFP Submitted','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106901','powerrfpapproved',110050,'DATETIME','powerrfpapproved','2','Power RFP Approved','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106910','powerpaymentplan',110080,'DATETIME','powerpaymentplan','2','Power Payment Plan','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106930','powerpaymentrfprel',110110,'DATETIME','powerpaymentrfprel','2','Power RFP Released','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106960','lineconstruction',110140,'DATETIME','lineconstruction','2','Line Construction','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106990','energizedplan',110170,'DATETIME','energizedplan','2','Energized Plan','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107020','siteenergized',110200,'DATETIME','siteenergized','2','Site Energized','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107050','electricalpat',110230,'DATETIME','electricalpat','2','Electrical PAT','2','SITE ENERGIZATION (PERMANENT POWER)','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107051','ntccode',110260,'VARCHAR(100)','ntccode','0','NTC Code','1','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107052','l700submitted',110290,'DATETIME','l700submitted','2','L700 Submitted','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107053','l2100submitted',110320,'DATETIME','l2100submitted','2','L2100 Submitted','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107054','l2600submitted',110350,'DATETIME','l2600submitted','2','L2600 Submitted','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107055','nrsubmitted',110380,'DATETIME','nrsubmitted','2','NR Submitted','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107056','enbpppsubmitted',110410,'DATETIME','enbpppsubmitted','2','eNB PPP Submitted','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107057','l700applied',110440,'DATETIME','l700applied','2','L700 Applied','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107058','l2100applied',110470,'DATETIME','l2100applied','2','L2100 Applied','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107059','l2600applied',110500,'DATETIME','l2600applied','2','L2600 Applied','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107060','nrapplied',110530,'DATETIME','nrapplied','2','NR Applied','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107061','enbpppapplied',110560,'DATETIME','enbpppapplied','2','eNB PPP Applied','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107062','l700permitreceived',110590,'DATETIME','l700permitreceived','2','L700 Permit Received','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107063','l2100permitreceived',110620,'DATETIME','l2100permitreceived','2','L2100 Permit Received','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107064','l2600permitreceived',110650,'DATETIME','l2600permitreceived','2','L2600 Permit Received','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107065','nrpermitreceived',110680,'DATETIME','nrpermitreceived','2','NR Permit Received','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107066','enbpppreceived',110710,'DATETIME','enbpppreceived','2','eNB PPP Received','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107067','mwpppsubmitted',110740,'DATETIME','mwpppsubmitted','2','MW PPP Submitted','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107068','mwpppapplied',110770,'DATETIME','mwpppapplied','2','MW PPP Applied','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107069','mwpppreceived',110800,'DATETIME','mwpppreceived','2','MW PPP Received','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107070','rslapplied',110830,'DATETIME','rslapplied','2','RSL Applied','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107071','rslreceived',110860,'DATETIME','rslreceived','2','RSL Received','2','NTC APPLICATION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107072','txvendor',110890,'VARCHAR(100)','txvendor','0','TX Vendor','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106240','txsolution',110920,'VARCHAR(100)','txsolution','0','TX Type','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106250','fiberconstructiion',110950,'VARCHAR(100)','fiberconstructiion','0','Fiber Source','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106251','aendtype',110980,'VARCHAR(100)','aendtype','0','A End Type','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106252','bside',111010,'VARCHAR(100)','bside','0','B Side(Backbone/Machine Type/Base Station Name)','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106253','bendtype',111040,'VARCHAR(100)','bendtype','0','B End Type','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106254','accesstype',111070,'VARCHAR(100)','accesstype','0','Access Type','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106255','opticalcablesegment',111100,'VARCHAR(100)','opticalcablesegment','0','Optical Cable Segment','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106256','opticalcablecluster',111130,'VARCHAR(100)','opticalcablecluster','0','Optical Cable Cluster','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106257','opticalcabletype',111160,'VARCHAR(100)','opticalcabletype','0','Optical Cable Type','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106258','opticalcablecores',111190,'VARCHAR(100)','opticalcablecores','0','Number of Optical Cable Cores','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106259','opticalcableplan',111220,'VARCHAR(100)','opticalcableplan','0','Optical Cable Planning Length','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106260','designroutelength',111250,'VARCHAR(100)','designroutelength','0','Design Route Length(km) ','1','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106261','rowapplied',111280,'DATETIME','rowapplied','2','ROW Applied','2','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106262','rowapproved',111310,'DATETIME','rowapproved','2','ROW Approved','2','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106850','jpartaapplied',111340,'DATETIME','jpartaapplied','2','JPA/RTA Applied','2','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106860','jpartaacquired',111370,'DATETIME','jpartaacquired','2','JPA/RTA Acquired','2','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106861','poleconcompleted',111400,'DATETIME','poleconcompleted','2','Pole Construction Completed','2','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106862','foclayingcompleted',111430,'DATETIME','foclayingcompleted','2','FOC Laying Completed','2','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106863','ipraninstalled',111460,'DATETIME','ipraninstalled','2','IPRAN Installed','2','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106864','mwinstalled',111490,'DATETIME','mwinstalled','2','MW Installed','2','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106865','txinstalledplan',111520,'DATETIME','txinstalledplan','2','TX Installed Plan','2','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106270','txinstalled',111550,'DATETIME','txinstalled','2','TX Installed','2','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106271','backhaulingavailable',111580,'DATETIME','backhaulingavailable','2','Backhauling Available','2','TRANSMISSION','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106272','mtfvalidated',111610,'DATETIME','mtfvalidated','2','MTF Validated','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106273','materialspartialdelivered',111640,'DATETIME','materialspartialdelivered','2','Materials Partial Delivered','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106274','materialsfulldelivered',111670,'DATETIME','materialsfulldelivered','2','Materials Full Delivered','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106300','mosplan',111700,'DATETIME','mosplan','2','MOS Plan','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106330','mos',111730,'DATETIME','mos','2','MOS','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106331','oduinstalledplan',111760,'DATETIME','oduinstalledplan','2','ODU Installed Plan','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106332','oduinstalled',111790,'DATETIME','oduinstalled','2','ODU Installed','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106333','btsinstalledplan',111820,'DATETIME','btsinstalledplan','2','BTS Installed Plan','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106360','btsinstallation',111850,'DATETIME','btsinstallation','2','BTS Installed','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106390','iciplan',111880,'DATETIME','iciplan','2','Integrated Plan','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106420','integrated',111910,'DATETIME','integrated','2','Integrated','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106450','rfsplan',111940,'DATETIME','rfsplan','2','RFS Plan','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106480','rfs',111970,'DATETIME','rfs','2','RFS','2','TELECOM WORKS','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106481','drivetestcompleted',112000,'DATETIME','drivetestcompleted','2','Drive Test Completed','2','RF ACCEPTANCE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106570','ssvplan',112030,'DATETIME','ssvplan','2','SSV Plan','2','RF ACCEPTANCE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106600','ssvapproved',112060,'DATETIME','ssvapproved','2','SSV Approved','2','RF ACCEPTANCE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106720','cacplan',112090,'DATETIME','cacplan','2','CAC Plan','2','RF ACCEPTANCE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106730','clusteracceptance',112120,'DATETIME','clusteracceptance','2','CAC','2','RF ACCEPTANCE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106731','prepat',112150,'DATETIME','prepat','2','Pre-PAT','2','SITE ACCEPTANCE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106510','patplan',112180,'DATETIME','patplan','2','PAT Plan','2','SITE ACCEPTANCE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106540','patapproved',112210,'DATETIME','patapproved','2','PAT Approved','2','SITE ACCEPTANCE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106690','pacplan',112240,'DATETIME','pacplan','2','PAC Plan','2','SITE ACCEPTANCE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106700','provisionalacceptance',112270,'DATETIME','provisionalacceptance','2','PAC','2','SITE ACCEPTANCE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106740','facplan',112300,'DATETIME','facplan','2','FAC Plan','2','SITE ACCEPTANCE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('106750','finalacceptance',112330,'DATETIME','finalacceptance','2','FAC','2','SITE ACCEPTANCE','0','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107170','extendt01',112360,'VARCHAR(100)','extendt01','0','extendt01','1','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107200','extendt02',112390,'VARCHAR(100)','extendt02','0','extendt02','1','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107230','extendt03',112420,'VARCHAR(100)','extendt03','0','extendt03','1','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107260','extendt04',112450,'VARCHAR(100)','extendt04','0','extendt04','1','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107290','extendt05',112480,'VARCHAR(100)','extendt05','0','extendt05','1','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107320','extendt06',112510,'VARCHAR(100)','extendt06','0','extendt06','1','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107350','extendt07',112540,'VARCHAR(100)','extendt07','0','extendt07','1','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107380','extendt08',112570,'VARCHAR(100)','extendt08','0','extendt08','1','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107410','extendt09',112600,'VARCHAR(100)','extendt09','0','extendt09','1','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107440','extendt10',112630,'VARCHAR(100)','extendt10','0','extendt10','1','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107770','extendi01',112660,'DECIMAL(10,0)','extendi01','1','extendi01','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107800','extendi02',112690,'DECIMAL(10,0)','extendi02','1','extendi02','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107830','extendi03',112720,'DECIMAL(10,0)','extendi03','1','extendi03','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107860','extendi04',112750,'DECIMAL(10,0)','extendi04','1','extendi04','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('107890','extendi05',112780,'DECIMAL(10,0)','extendi05','1','extendi05','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108370','extendd01',112810,'DATETIME','extendd01','2','extendd01','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108400','extendd02',112840,'DATETIME','extendd02','2','extendd02','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108430','extendd03',112870,'DATETIME','extendd03','2','extendd03','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108460','extendd04',112900,'DATETIME','extendd04','2','extendd04','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108490','extendd05',112930,'DATETIME','extendd05','2','extendd05','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108520','extendd06',112960,'DATETIME','extendd06','2','extendd06','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108550','extendd07',112990,'DATETIME','extendd07','2','extendd07','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108580','extendd08',113020,'DATETIME','extendd08','2','extendd08','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108610','extendd09',113050,'DATETIME','extendd09','2','extendd09','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108640','extendd10',113080,'DATETIME','extendd10','2','extendd10','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108670','extendd11',113110,'DATETIME','extendd11','2','extendd11','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108700','extendd12',113140,'DATETIME','extendd12','2','extendd12','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108730','extendd13',113170,'DATETIME','extendd13','2','extendd13','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108760','extendd14',113200,'DATETIME','extendd14','2','extendd14','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108790','extendd15',113230,'DATETIME','extendd15','2','extendd15','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108820','extendd16',113260,'DATETIME','extendd16','2','extendd16','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108850','extendd17',113290,'DATETIME','extendd17','2','extendd17','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108880','extendd18',113320,'DATETIME','extendd18','2','extendd18','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108910','extendd19',113350,'DATETIME','extendd19','2','extendd19','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('108940','extendd20',113380,'DATETIME','extendd20','2','extendd20','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109870','extendn01',113410,'DECIMAL(8,6)','extendn01','4','extendn01','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109900','extendn02',113440,'DECIMAL(8,6)','extendn02','4','extendn02','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109930','extendn03',113470,'DECIMAL(8,6)','extendn03','4','extendn03','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109960','extendn04',113500,'DECIMAL(8,6)','extendn04','4','extendn04','2','Extend','1','system',now(),'system',now(),'');
INSERT INTO yc_site_column VALUES ('109990','extendn05',113530,'DECIMAL(8,6)','extendn05','4','extendn05','2','Extend','1','system',now(),'system',now(),'');
