insert into yc_accep_model values(1001,  10, 'Template a', 'a', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1002,  20, 'Template b', 'b', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1003,  30, 'Template c', 'c', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1004,  40, 'Template d', 'd', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1005,  50, 'Template e', 'e', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1006,  60, 'Template f', 'f', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1007,  70, 'Template g', 'g', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1008,  80, 'Template h', 'h', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1009,  90, 'Template i', 'i', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1010, 100, 'Template j', 'j', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1011, 110, 'Template k', 'k', null, null, null, 1, 'system', now(), 'system', now(), null);


delete from yc_site_twodir;
insert into yc_site_twodir value ('200','200','Construction Prelims');
insert into yc_site_twodir value ('230','230','Tower Foundation');
insert into yc_site_twodir value ('260','260','Tower Erection');
insert into yc_site_twodir value ('290','290','Site Development Works');
insert into yc_site_twodir value ('320','320','Temporary Power');
insert into yc_site_twodir value ('350','350','Antenna System and GPS System');
insert into yc_site_twodir value ('380','380','Base Station Equipment');
insert into yc_site_twodir value ('410','410','Cable Installation');
insert into yc_site_twodir value ('440','440','Integrated Cabinet');
insert into yc_site_twodir value ('470','470','Commercial Power');
insert into yc_site_twodir value ('500','500','Provisional Acceptance (CW)');
insert into yc_site_twodir value ('530','530','Provisional Acceptance (TE)');
insert into yc_site_twodir value ('560','560','Provisional Acceptance (CPA)');


delete from yc_site_dir;
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1000','1000','200','SKOM','1_SKOM');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1100','1100','200','Mobilization','2_Mobilization');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1200','1200','200','Excavation','3_Excavation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1300','1300','200','Rebar Preparation','4_Rebar Preparation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1400','1400','230','Rebar Installation (Footing)','1_Rebar Installation (Footing)');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1500','1500','230','Concrete Pouring (Footing)','2_Concrete Pouring (Footing)');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1600','1600','230','Concrete Curing (Footing)','3_Concrete Curing (Footing)');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1700','1700','230','Rebar Installation (Pedestal)','4_Rebar Installation (Pedestal)');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1800','1800','230','Anchor Bolts Installation','5_Anchor Bolts Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1900','1900','230','Pedestal Concrete Pouring','6_Pedestal Concrete Pouring');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2000','2000','230','Pedestal Concrete Curing','7_Pedestal Concrete Curing');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2100','2100','260','Backfilling (Greenfield)','1_Backfilling (Greenfield)');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2200','2200','260','Tower Erection','2_Tower Erection');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2300','2300','260','Tower Verticality','3_Tower Verticality');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2400','2400','260','Tower Erection Completed','4_Tower Erection Completed');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2500','2500','260','Tower Torque Test','5_Tower Torque Test');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2600','2600','290','C-channel Installation','1_C-channel Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2650','2650','290','ODU Pad Construction','1_ODU Pad Construction');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2700','2700','290','Grounding Installation','2_Grounding Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2800','2800','290','Grounding Test','3_Grounding Test');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2900','2900','290','Electrical Installation','4_Electrical Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3000','3000','290','Site Development','5_Site Development');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3100','3100','290','Gate Installation','6_Gate Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3200','3200','290','Perimeter Barbed Wire Installation','7_Perimeter Barbed Wire Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3300','3300','290','Perimeter Light Installation','8_Perimeter Light Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3400','3400','290','Aviation Light Installation','9_Aviation Light Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3500','3500','290','FOC Handhole Installation','10_FOC Handhole Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3600','3600','320','Temporary Power Meter','1_Temporary Power Meter');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3700','3700','320','Electricity Checking','2_Electricity Checking');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3800','3800','320','Airswitch, Cable Specification & Model','3_Airswitch, Cable Specification & Model');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3900','3900','320','Cable Laying','4_Cable Laying');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4000','4000','320','Temporary Power Connection Agreement','5_Temporary Power Connection Agreement');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4100','4100','350','Antenna Overview','1_Antenna Overview');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4200','4200','350','Antenna Azimuth','2_Antenna Azimuth');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4300','4300','350','Mechanical Tilt of the Antenna','3_Mechanical Tilt of the Antenna');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4400','4400','350','Remote RET Antenna Test','4_Remote RET Antenna Test');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4500','4500','350','GPS System','5_GPS System');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4600','4600','380','Test Record','1_Test Record');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4700','4700','380','RRU Overview','2_RRU Overview');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4800','4800','380','RRU Installation ','3_RRU Installation ');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4900','4900','380','BBU Overview','4_BBU Overview');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5000','5000','380','BBU Labels','5_BBU Labels');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5100','5100','380','BBU Installation ','6_BBU Installation ');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5200','5200','410','Cabling on the RRU Side','1_Cabling on the RRU Side');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5300','5300','410','Cable Clip','2_Cable Clip');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5400','5400','410','Route Cables into the Cabinet 1','3_Route Cables into the Cabinet 1');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5500','5500','410','Route Cables into the Cabinet 2','4_Route Cables into the Cabinet 2');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5600','5600','440','Outdoor Cabinet Installation of Air Conditioner, Heat Exchanger & Monitoring Unit','1_Outdoor Cabinet Installation of Air Conditioner, Heat Exchanger & Monitoring Unit');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5700','5700','440','Outdoor Integrated Power Cabinet Installation','2_Outdoor Integrated Power Cabinet Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5800','5800','440','Cabinet Equipment Compartment Installation','3_Cabinet Equipment Compartment Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5900','5900','440','Cabinet Battery Compartment Installation','4_Cabinet Battery Compartment Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6000','6000','440','Cabinet AC Input Warning Flag','5_Cabinet AC Input Warning Flag');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6100','6100','440','Cable Inlet of Cabinet','6_Cable Inlet of Cabinet');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6200','6200','440','LED Light of Cabinet','7_LED Light of Cabinet');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6300','6300','440','Sensor Installation','8_Sensor Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6400','6400','440','Asset Label','9_Asset Label');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6500','6500','440','ODF Installation','10_ODF Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6600','6600','470','Commercial Power Meter','1_Commercial Power Meter');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6700','6700','470','Electricity Checking','2_Electricity Checking');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6800','6800','470','Service Entrance Pedestal','3_Service Entrance Pedestal');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6900','6900','470','Transformer Installation','4_Transformer Installation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7000','7000','470','Air Circuit Breaker','5_Air Circuit Breaker');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7100','7100','470','Cable Laying','6_Cable Laying');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7200','7200','470','Commercial Power Contract','7_Commercial Power Contract');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7300','7300','500','Civil Works Completion Report','10_Civil Works Completion Report');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7400','7400','500','Pre-PAT Checklist','20_Pre-PAT Checklist');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7500','7500','500','Rectification Report','30_Rectification Report');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7600','7600','530','TE Completion Report','10_TE Completion Report');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7700','7700','530','SSV Minutes Report','20_SSV Minutes Report');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7800','7800','530','Pre-PAT Checklist','30_Pre-PAT Checklist');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7900','7900','530','Rectification Report','40_Rectification Report');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8000','8000','560','Power Completion Report','10_Power Completion Report');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8100','8100','560','SLD','20_SLD');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8200','8200','560','Rectification Report','30_Rectification Report');


