insert into yc_accep_model values(1001,  10, 'Template a', 'a', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1002,  20, 'Template b', 'b', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1003,  30, 'Template c', 'c', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1004,  40, 'Template d', 'd', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1005,  50, 'Template e', 'e', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1006,  60, 'Template f', 'f', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1007,  70, 'Template g', 'g', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1008,  80, 'Template h', 'h', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1009,  90, 'Template i', 'i', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1010, 100, 'Template j', 'j', null, null, null, 1, 'system', now(), 'system', now(), null);
insert into yc_accep_model values(1011, 110, 'Template k', 'k', null, null, null, 1, 'system', now(), 'system', now(), null);



delete from yc_site_twodir;
insert into yc_site_twodir value ('200','200','Tower Civil Work');
insert into yc_site_twodir value ('230','230','Tower Body');
insert into yc_site_twodir value ('260','260','Tower Foundation');
insert into yc_site_twodir value ('290','290','Tower Grounding');
insert into yc_site_twodir value ('320','320','External Power Acept Form');
insert into yc_site_twodir value ('350','350','Temporary Power  Acept Form');
insert into yc_site_twodir value ('380','380','Antenna System and GPS System');
insert into yc_site_twodir value ('410','410','Base Station Equipment');
insert into yc_site_twodir value ('440','440','Cable Installation');
insert into yc_site_twodir value ('470','470','Record Files');
insert into yc_site_twodir value ('500','500','Integrated Cabinet');

delete from yc_site_dir;
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1000','1000','200','Casting the Cabinet Pad','1_Castingthecabinetpad');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1100','1100','200','Site Restoration & Water Proofing','2_Siterestoration&Waterproofing');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1200','1200','200','Protective Installation (GF)','3_Protectiveinstallation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1300','1300','200','Water Drainage（GF）','4_Waterdrainage');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1400','1400','200','MCB or MTS Installation','5_Mcbormtsinstallation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1500','1500','200','ACPDB Installtion & Grounding','6_Acpdbinstalltion&Grounding');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1600','1600','230','Tower Main Body','4_Towermainbody');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1700','1700','230','Tower Verticality','2_Towerverticality');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1800','1800','230','Dimensions of Tower & Mast Components','1_Dimensionsoftower&Mastcomponents');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('1900','1900','230','Aviation Light','5_Aviationlight');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2000','2000','230','Aviation Light Wiring','6_Aviationlightwiring');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2100','2100','230','Antenna Bracket & Platform','7_Antennabracket&Platform');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2200','2200','230','Exposed Bolt Screw','8_Exposedboltscrew');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2300','2300','230','Cable Tray','9_Cabletray');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2400','2400','230','Tower foot Bolt','10_Towerfootbolt');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2500','2500','230','Lightning Arrestor 1','11_Lightningarrestor1');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2600','2600','230','Lightning Arrestor 2','12_Lightningarrestor2');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2700','2700','230','Lightning Arrestor 3','13_Lightningarrestor3');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2800','2800','260','Documents Check 1','1_Documentscheck1');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('2900','2900','260','Documents Check 2','2_Documentscheck2');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3000','3000','260','Documents Check 3','3_Documentscheck3');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3100','3100','260','Rebar Material','4_Rebarmaterial');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3200','3200','260','Rebar Work','5_Rebarwork');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3300','3300','260','Concrete Material','6_Concretematerial');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3400','3400','260','Implanted Steel Bar Foundation','7_Implantedsteelbarfoundation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3500','3500','260','Concrete Strength','8_Concretestrength');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3600','3600','260','Foundation Settlement (GF)','9_Foundationsettlement');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3700','3700','260','Height of Each Tower Foot','10_Heightofeachtowerfoot');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3800','3800','260','Quality of Tower Foundation','11_Qualityoftowerfoundation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('3900','3900','260','Concrete Beam Foundation (If Applicable)','12_Concretebeamfoundation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4000','4000','260','Steel Beam Foundation (If Applicable)','13_Steelbeamfoundation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4100','4100','260','Building Beam or Column Reinforcement (If Necessary)','14_Buildingbeamorcolumnreinforce');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4200','4200','260','Backfill Soil Compaction (GF)','15_Backfillsoilcompaction');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4300','4300','290','Proof of Materials','1_Proofofmaterials');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4400','4400','290','Burial Depth of Vertical Grounding Rod Overall Layout (Pictures)','2_Burialdepthofverticalgrounding');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4500','4500','290','Lightning Protection & Grounding Connection','3_Lightningprotection&Grounding');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4600','4600','290','Anti Corrosion of Lightning Protection & Grounding System','4_Anticorrosionoflightning');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4700','4700','290','Bus Bar Installation Process','5_Busbarinstallationprocess');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4800','4800','290','Grounding Resistance Test','6_Groundingresistancetest');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('4900','4900','290','Number & Positions of Flat Steel Lead-out from the Grounding Grid','7_Number&Positionsofflat');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5000','5000','290','Electricity Supply System Grounding','8_Electricitysupplysystemgrounding');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5100','5100','290','Feeder Cable Grounding (Optional, If Applicable)','9_Feedercablegrounding');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5200','5200','320','Signed Commercial Power Application & Supply Services','1_Signedcommercialpower');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5300','5300','320','Electricity Checking','2_Electricitychecking');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5400','5400','320','Commercial Power Meter','3_Commercialpowermeter');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5500','5500','320','Service Entrance Pedestal','4_Serviceentrancepedestal');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5600','5600','320','Airswitch, Cable Specification & Model','5_Airswitchcablespecification&M');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5700','5700','320','Cable Laying','6_Cablelaying');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5800','5800','350','Temporary Power Connection Agreement','1_Temporarypowerconnectionagreemt');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('5900','5900','350','Temporary Power Meter (If Applicable)','2_Temporarypowermeter');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6000','6000','350','Electricity Checking','3_ElectricitycheckingTP');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6100','6100','350','Airswitch, Cable Specification & Model','4_Airswitchcablespecification&Model');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6200','6200','350','Cable Laying','5_CablelayingTP');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6300','6300','350','Power usage analysis','6_Powerusageanalysis');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6400','6400','380','Antenna Installation Position','1_Antennainstallationposition');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6500','6500','380','Antenna azimuth','2_Antennaazimuth');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6600','6600','380','Mechanical tilt of the antenna','3_Mechanicaltiltoftheantenna');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6700','6700','380','Remote RET Antenna Test','5_Remoteretantennatest');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6800','6800','380','GPS system 1','6_Gpssystem1');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('6900','6900','380','GPS system 2','7_Gpssystem2');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7000','7000','380','GPS system 3','8_Gpssystem3');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7100','7100','380','GPS system 4','9_Gpssystem4');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7200','7200','380','spacing','10_Spacing');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7300','7300','410','Test Record','1_Testrecord');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7400','7400','410','RRU Installation1','2_Rruinstallation1');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7500','7500','410','RRU Installation2','3_Rruinstallation2');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7600','7600','410','BBU Installation1','4_Bbuinstallation1');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7700','7700','410','BBU Installation2','5_Bbuinstallation2');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7800','7800','410','BBU Installation3','6_Bbuinstallation3');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('7900','7900','410','label','7_Label');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8000','8000','440','Cabling on the RRU side','1_Cablingontherruside');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8100','8100','440','Cabling on the BBU side','2_Cablingonthebbuside');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8200','8200','440','Cable Clip','3_Cableclip');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8300','8300','440','Grounding cable on the tower','4_Groundingcableonthetower');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8400','8400','440','Route Cables Into the Cabinet 1','5_Routecablesintothecabinet1');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8500','8500','440','Route Cables Into the Cabinet 2','6_Routecablesintothecabinet2');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8600','8600','440','Label Inside the Cabinet','7_Labelinsidethecabinet');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8700','8700','470','Design Documents','2_Designdocuments');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8800','8800','470','Material List','3_Materiallist');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('8900','8900','470','Minutes of Construction Drawings Review','1_Minutesofconstructiondrawingsreview');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('9000','9000','470','Single Site Verification Report','5_Singlesiteverificationreport');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('9100','9100','470','Resource Completion Information','6_Resourcecompletioninformation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('9200','9200','470','Design Change Records (If Any)','7_Designchangerecords');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('9300','9300','470','Construction Deviation (If Any)','8_Constructiondeviation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('9400','9400','470','Construction Defects (If Any)','9_Constructiondefects');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('9500','9500','470','Supervision Random Inspection Records (If Any)','10_Supervisionrandominspectionrecords');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('9600','9600','500','Outdoor Cabinet Installation of Air Conditioner, Heat Exchanger & Monitoring Unit','1_Outdoorcabinetinstallationofaircon');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('9700','9700','500','Outdoor Integrated Power Cabinet Installation','2_Outdoorintegratedpowercabinst');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('9800','9800','500','Outdoor Integrated Power Cabinet Installation at Fix Position','3_Outdoorintegratedpowercabinsatfix');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('9900','9900','500','Cabinet Equipment Compartment Installation','4_Cabinetequipmentcompartmentinst');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('10000','10000','500','Cabinet Battery Compartment Installation','5_Cabinetbatterycompartmentinst');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('10100','10100','500','Cabinet AC Input Warning Flag','6_Cabinetacinputwarningflag');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('10200','10200','500','Cabinet Grounding','7_Cabinetgrounding');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('10300','10300','500','Cable Inlet of Cabinet','8_Cableinletofcabinet');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('10400','10400','500','LED Light of Cabinet','9_Ledlightofcabinet');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('10500','10500','500','Sensor Installation','10_Sensorinstallation');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('10600','10600','500','Operating Temperature & Humidity','11_Operatingtemperature&Humidity');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('10700','10700','500','Label','12_LabelIC');
insert into yc_site_dir(id,sort,two_dir_id,three_dir,dir_name) value ('10800','10800','500','ODM installation(If any)','13_Odminstallation');