DROP TABLE IF EXISTS ycosp_report_a;
CREATE TABLE ycosp_report_a
(
	id				VARCHAR(64)		NOT NULL	COMMENT 'ID',
	rpt_type		VARCHAR(64)		NOT NULL	COMMENT '',
	sort			DECIMAL(10,0)	NOT NULL	COMMENT '',
	str_a			VARCHAR(100)		NULL	COMMENT '',
	str_b			VARCHAR(100)		NULL	COMMENT '',
	str_c			VARCHAR(100)		NULL	COMMENT '',
	str_d			VARCHAR(100)		NULL	COMMENT '',
	int_a			DECIMAL(10,0)		NULL	COMMENT '',
	int_b			DECIMAL(10,0)		NULL	COMMENT '',
	int_c			DECIMAL(10,0)		NULL	COMMENT '',
	int_d			DECIMAL(10,0)		NULL	COMMENT '',
	int_e			DECIMAL(10,0)		NULL	COMMENT '',
	int_f			DECIMAL(10,0)		NULL	COMMENT '',
	int_g			DECIMAL(10,0)		NULL	COMMENT '',
	int_h			DECIMAL(10,0)		NULL	COMMENT '',
	int_i			DECIMAL(10,0)		NULL	COMMENT '',
	int_j			DECIMAL(10,0)		NULL	COMMENT '',
	int_k			DECIMAL(10,0)		NULL	COMMENT '',
	int_l			DECIMAL(10,0)		NULL	COMMENT '',
	int_m			DECIMAL(10,0)		NULL	COMMENT '',
	int_n			DECIMAL(10,0)		NULL	COMMENT '',
	int_o			DECIMAL(10,0)		NULL	COMMENT '',
	int_p			DECIMAL(10,0)		NULL	COMMENT '',
	int_q			DECIMAL(10,0)		NULL	COMMENT '',
	int_r			DECIMAL(10,0)		NULL	COMMENT '',
	int_s			DECIMAL(10,0)		NULL	COMMENT '',
	int_t			DECIMAL(10,0)		NULL	COMMENT '',
	PRIMARY KEY (id)
) COMMENT = 'ycosp_report_a';



DROP TABLE IF EXISTS ycosp_report_b;
CREATE TABLE ycosp_report_b
(
	id				VARCHAR(64)		NOT NULL	COMMENT 'ID',
	rpt_type		VARCHAR(64)		NOT NULL	COMMENT '',
	sort			DECIMAL(10,0)	NOT NULL	COMMENT '',
	str_a			VARCHAR(100)		NULL	COMMENT '',
	str_b			VARCHAR(100)		NULL	COMMENT '',
	str_c			VARCHAR(100)		NULL	COMMENT '',
	str_d			VARCHAR(100)		NULL	COMMENT '',
	int_a			DECIMAL(10,0)		NULL	COMMENT '',
	int_b			DECIMAL(10,0)		NULL	COMMENT '',
	int_c			DECIMAL(10,0)		NULL	COMMENT '',
	int_d			DECIMAL(10,0)		NULL	COMMENT '',
	int_e			DECIMAL(10,0)		NULL	COMMENT '',
	int_f			DECIMAL(10,0)		NULL	COMMENT '',
	int_g			DECIMAL(10,0)		NULL	COMMENT '',
	int_h			DECIMAL(10,0)		NULL	COMMENT '',
	int_i			DECIMAL(10,0)		NULL	COMMENT '',
	int_j			DECIMAL(10,0)		NULL	COMMENT '',
	int_k			DECIMAL(10,0)		NULL	COMMENT '',
	int_l			DECIMAL(10,0)		NULL	COMMENT '',
	int_m			DECIMAL(10,0)		NULL	COMMENT '',
	int_n			DECIMAL(10,0)		NULL	COMMENT '',
	int_o			DECIMAL(10,0)		NULL	COMMENT '',
	int_p			DECIMAL(10,0)		NULL	COMMENT '',
	int_q			DECIMAL(10,0)		NULL	COMMENT '',
	int_r			DECIMAL(10,0)		NULL	COMMENT '',
	int_s			DECIMAL(10,0)		NULL	COMMENT '',
	int_t			DECIMAL(10,0)		NULL	COMMENT '',
	PRIMARY KEY (id)
) COMMENT = 'ycosp_report_b';


DROP TABLE IF EXISTS ycosp_report_c;
CREATE TABLE ycosp_report_c
(
	id				VARCHAR(64)		NOT NULL	COMMENT 'ID',
	rpt_type		VARCHAR(64)		NOT NULL	COMMENT '',
	sort			DECIMAL(10,0)	NOT NULL	COMMENT '',
	str_a			VARCHAR(100)		NULL	COMMENT '',
	str_b			VARCHAR(100)		NULL	COMMENT '',
	str_c			VARCHAR(100)		NULL	COMMENT '',
	str_d			VARCHAR(100)		NULL	COMMENT '',
	int_a			DECIMAL(10,0)		NULL	COMMENT '',
	int_b			DECIMAL(10,0)		NULL	COMMENT '',
	int_c			DECIMAL(10,0)		NULL	COMMENT '',
	int_d			DECIMAL(10,0)		NULL	COMMENT '',
	int_e			DECIMAL(10,0)		NULL	COMMENT '',
	int_f			DECIMAL(10,0)		NULL	COMMENT '',
	int_g			DECIMAL(10,0)		NULL	COMMENT '',
	int_h			DECIMAL(10,0)		NULL	COMMENT '',
	int_i			DECIMAL(10,0)		NULL	COMMENT '',
	int_j			DECIMAL(10,0)		NULL	COMMENT '',
	int_k			DECIMAL(10,0)		NULL	COMMENT '',
	int_l			DECIMAL(10,0)		NULL	COMMENT '',
	int_m			DECIMAL(10,0)		NULL	COMMENT '',
	int_n			DECIMAL(10,0)		NULL	COMMENT '',
	int_o			DECIMAL(10,0)		NULL	COMMENT '',
	int_p			DECIMAL(10,0)		NULL	COMMENT '',
	int_q			DECIMAL(10,0)		NULL	COMMENT '',
	int_r			DECIMAL(10,0)		NULL	COMMENT '',
	int_s			DECIMAL(10,0)		NULL	COMMENT '',
	int_t			DECIMAL(10,0)		NULL	COMMENT '',
	int_u			DECIMAL(10,0)		NULL	COMMENT '',
	int_v			DECIMAL(10,0)		NULL	COMMENT '',
	int_w			DECIMAL(10,0)		NULL	COMMENT '',
	int_x			DECIMAL(10,0)		NULL	COMMENT '',
	int_y			DECIMAL(10,0)		NULL	COMMENT '',
	int_z			DECIMAL(10,0)		NULL	COMMENT '',
	int_aa			DECIMAL(10,0)		NULL	COMMENT '',
	int_ab			DECIMAL(10,0)		NULL	COMMENT '',
	int_ac			DECIMAL(10,0)		NULL	COMMENT '',
	int_ad			DECIMAL(10,0)		NULL	COMMENT '',
	int_ae			DECIMAL(10,0)		NULL	COMMENT '',
	int_af			DECIMAL(10,0)		NULL	COMMENT '',
	int_ag			DECIMAL(10,0)		NULL	COMMENT '',
	int_ah			DECIMAL(10,0)		NULL	COMMENT '',
	int_ai			DECIMAL(10,0)		NULL	COMMENT '',
	int_aj			DECIMAL(10,0)		NULL	COMMENT '',
	int_ak			DECIMAL(10,0)		NULL	COMMENT '',
	int_al			DECIMAL(10,0)		NULL	COMMENT '',
	int_am			DECIMAL(10,0)		NULL	COMMENT '',
	int_an			DECIMAL(10,0)		NULL	COMMENT '',
	int_ao			DECIMAL(10,0)		NULL	COMMENT '',
	int_ap			DECIMAL(10,0)		NULL	COMMENT '',
	int_aq			DECIMAL(10,0)		NULL	COMMENT '',
	int_ar			DECIMAL(10,0)		NULL	COMMENT '',
	int_as			DECIMAL(10,0)		NULL	COMMENT '',
	int_at			DECIMAL(10,0)		NULL	COMMENT '',
	int_au			DECIMAL(10,0)		NULL	COMMENT '',
	int_av			DECIMAL(10,0)		NULL	COMMENT '',
	int_aw			DECIMAL(10,0)		NULL	COMMENT '',
	int_ax			DECIMAL(10,0)		NULL	COMMENT '',
	int_ay			DECIMAL(10,0)		NULL	COMMENT '',
	int_az			DECIMAL(10,0)		NULL	COMMENT '',
	int_ba			DECIMAL(10,0)		NULL	COMMENT '',
	int_bb			DECIMAL(10,0)		NULL	COMMENT '',
	int_bc			DECIMAL(10,0)		NULL	COMMENT '',
	PRIMARY KEY (id)
) COMMENT = 'ycosp_report_c';
