DROP TABLE IF EXISTS ycdc_site;
CREATE TABLE ycdc_site (
	id					VARCHAR(100)	NOT NULL	COMMENT 'ID',
	physicalplansiteid	VARCHAR(64)	NOT NULL	COMMENT 'Site ID',
	snnn	VARCHAR(100)	NULL	COMMENT 'S/N',
	longitude	DECIMAL(10,7)	NULL	COMMENT 'Longitude',
	latitude	DECIMAL(10,7)	NULL	COMMENT 'Latitude',
	sitetype	VARCHAR(100)	NULL	COMMENT 'Site Type',
	siteclassification	VARCHAR(100)	NULL	COMMENT 'Site Classification',
	area	VARCHAR(100)	NULL	COMMENT 'Area',
	region	VARCHAR(100)	NULL	COMMENT 'Region',
	province	VARCHAR(100)	NULL	COMMENT 'Province',
	city	VARCHAR(100)	NULL	COMMENT 'City/Municipality',
	barangay	VARCHAR(100)	NULL	COMMENT 'Barangay',
	saqvendor	VARCHAR(100)	NOT NULL	COMMENT 'SAQ Vendor',
	saqponumber	VARCHAR(100)	NULL	COMMENT 'SAQ PO Number',
	tssdddvendor	VARCHAR(100)	NULL	COMMENT 'TSS/DDD Vendor',
	tssdddponumber	VARCHAR(100)	NULL	COMMENT 'TSS/DDD PO Number',
	cmevendor	VARCHAR(100)	NULL	COMMENT 'CME Vendor',
	cmeponumber	VARCHAR(100)	NULL	COMMENT 'CME PO Number',
	sarfissued	DATETIME	NULL	COMMENT 'SARF Issued',
	surveydoneplan	DATETIME	NULL	COMMENT 'Survey Done<br>Plan',
	surverydone	DATETIME	NULL	COMMENT 'Survery Done',
	sarsubmittedplan	DATETIME	NULL	COMMENT 'SAR Submitted<br>Plan',
	sarsubmittedoptiona	DATETIME	NULL	COMMENT 'SAR Submitted<br>Option A',
	sarsubmittedoptionb	DATETIME	NULL	COMMENT 'SAR Submitted<br>Option B',
	sarsubmitted	DATETIME	NULL	COMMENT 'SAR Submitted',
	sarapprovedplan	DATETIME	NULL	COMMENT 'SAR  Approved Plan',
	sarapprovedoptiona	DATETIME	NULL	COMMENT 'SAR Approved<br>Option A',
	sarapprovedoptionb	DATETIME	NULL	COMMENT 'SAR Approved<br>Option B',
	sarapproved	DATETIME	NULL	COMMENT 'SAR Approved',
	mocsignedoptiona	DATETIME	NULL	COMMENT 'MOC Signed<br>Option A',
	mocsignedoptionb	DATETIME	NULL	COMMENT 'MOC Signed<br>Option B',
	mocsignedoptionc	DATETIME	NULL	COMMENT 'MOC Signed<br>Option C',
	mocsignedoptiond	DATETIME	NULL	COMMENT 'MOC Signed<br>Option D',
	mocsigned	DATETIME	NULL	COMMENT 'MOC Signed',
	mocsubmitted	DATETIME	NULL	COMMENT 'MOC Submitted',
	mocapprovedplan	DATETIME	NULL	COMMENT 'MOC Approved<br>Plan',
	mocapproved	DATETIME	NULL	COMMENT 'MOC Approved',
	nrafsubmitted	DATETIME	NULL	COMMENT 'NRAF Submitted',
	nrafapprovedplan	DATETIME	NULL	COMMENT 'NRAF Approved<br>Plan',
	nrafapproved	DATETIME	NULL	COMMENT 'NRAF Approved',
	approvedoption	VARCHAR(100)	NULL	COMMENT 'Approved<br>Option',
	lessorname	VARCHAR(100)	NULL	COMMENT 'Lessor Name',
	streetbuilding	VARCHAR(100)	NULL	COMMENT 'Street/Building',
	actbarangay	VARCHAR(100)	NULL	COMMENT 'SI Barangay',
	citymunicipality	VARCHAR(100)	NULL	COMMENT 'SI City/Municipality',
	siprovince	VARCHAR(100)	 NULL	COMMENT 'SI Province',
	completesiteaddress	VARCHAR(255)	NULL	COMMENT 'Complete Site Address',
	silongitude	DECIMAL(10,7)	 NULL	COMMENT 'SI Longitude',
	silatitude	DECIMAL(10,7)	 NULL	COMMENT 'SI Latitude',
	sisitetype	VARCHAR(100)	 NULL	COMMENT 'SI Site Type',
	buildingheight	DECIMAL(10,2)	 NULL	COMMENT 'Building<br>Height (m)',
	periodoflease	VARCHAR(100)	 NULL	COMMENT 'Period of<br>Lease',
	monthlyrent	VARCHAR(100)	 NULL	COMMENT 'Monthly<br>Rent',
	taxprovision	VARCHAR(100)	 NULL	COMMENT 'Tax Provision',
	vatamount	VARCHAR(100)	 NULL	COMMENT 'VAT Amount<br>(12%)',
	whtamount	VARCHAR(100)	 NULL	COMMENT 'WHT Amount<br>(5%)',
	escalationrate	VARCHAR(100)	 NULL	COMMENT 'Escalation<br>Rate',
	advancerental	VARCHAR(100)	 NULL	COMMENT 'Advance<br>Rental',
	securitydeposit	VARCHAR(100)	 NULL	COMMENT 'Security<br>Deposit',
	securitydepositamo	VARCHAR(100)	 NULL	COMMENT 'Security Deposit Amount',
	modeofpayment	VARCHAR(100)	 NULL	COMMENT 'Mode of<br>Payment',
	leasearea	VARCHAR(100)	 NULL	COMMENT 'Lease Area',
	neighborsconsent	DATETIME	 NULL	COMMENT 'Neighbors<br>Consent',
	noneighborscertificate	DATETIME	 NULL	COMMENT 'No Neighbors<br>Certificate',
	nameofsubdivisionhoa	DATETIME	 NULL	COMMENT 'Name of<br>Subdivision/HOA',
	nameofhoapresident	DATETIME	 NULL	COMMENT 'Name of<br>HOA President',
	hoapresidentcontactno	DATETIME	 NULL	COMMENT 'HOA President<br>Contact No.',
	hoaclearancesecured	DATETIME	 NULL	COMMENT 'HOA Clearance<br>Secured',
	brappliedplan	DATETIME	 NULL	COMMENT 'BR Applied<br>Plan',
	brapplied	DATETIME	 NULL	COMMENT 'BR Applied',
	bcsecured	DATETIME	 NULL	COMMENT 'BC Secured',
	bcsecuredplan	DATETIME	 NULL	COMMENT 'BC Secured<br>Plan',
	brsecured	DATETIME	 NULL	COMMENT 'BR Secured',
	propdocsstartedplan	DATETIME	 NULL	COMMENT 'PropDocs Started<br>Plan',
	taxdeclarationsecured	DATETIME	 NULL	COMMENT 'Tax Declaration<br>Secured',
	taxclearancesecured	DATETIME	 NULL	COMMENT 'Tax Clearance<br>Secured',
	tctsecured	DATETIME	 NULL	COMMENT 'TCT<br>Secured',
	conceptualdrawingsigned	DATETIME	 NULL	COMMENT 'Conceptual Drawing Signed',
	lessorinformationsheet	DATETIME	 NULL	COMMENT 'Lessor Information Sheet',
	tpcaspca	VARCHAR(100)	 NULL	COMMENT 'TPCA / SPCA',
	lotsegregationplan	DATETIME	 NULL	COMMENT 'Lot Segregation Plan',
	lessorid	VARCHAR(100)	 NULL	COMMENT 'Lessor ID',
	draftcolplan	DATETIME	 NULL	COMMENT 'Draft COL<br>Plan',
	draftcolsigned	DATETIME	 NULL	COMMENT 'Draft COL<br>Signed',
	tinnn	VARCHAR(100)	 NULL	COMMENT 'TIN',
	bankaccountname	VARCHAR(100)	 NULL	COMMENT 'Bank Account Name',
	banknamebranch	VARCHAR(100)	 NULL	COMMENT 'Bank Name/Branch',
	bankaccountnumber	VARCHAR(100)	 NULL	COMMENT 'Bank Account Number',
	lessorcontact	VARCHAR(100)	 NULL	COMMENT 'Lessor Contact',
	lessoraddress	VARCHAR(100)	 NULL	COMMENT 'Lessor Address',
	landclassification	VARCHAR(100)	 NULL	COMMENT 'Land Classification',
	propdocsdoneplan	VARCHAR(100)	 NULL	COMMENT 'PropDocs Done<br>Plan',
	propertydocscompleted	DATETIME	 NULL	COMMENT 'Property Docs<br>Completed',
	propertydocssubmitted	DATETIME	 NULL	COMMENT 'Property Docs<br>Submitted',
	colreviewedbylegal	DATETIME	 NULL	COMMENT 'COL Reviewed<br>by Legal',
	colapprovedbylegal	DATETIME	 NULL	COMMENT 'COL Approved<br>by Legal',
	cspfsubmitted	DATETIME	 NULL	COMMENT 'CSPF<br>Submitted',
	cspfapproved	DATETIME	 NULL	COMMENT 'CSPF<br>Approved',
	colsignedbydito	DATETIME	 NULL	COMMENT 'COL Signed<br>by DITO',
	colsignedbylessor	DATETIME	 NULL	COMMENT 'COL Signed<br>by Lessor',
	colsignedplan	DATETIME	 NULL	COMMENT 'COL Signed<br>Plan',
	colsignedbybothparties	DATETIME	 NULL	COMMENT 'COL Signed by<br>Both Parties',
	rfpsubmitted	DATETIME	 NULL	COMMENT 'RFP<br>Submitted',
	rfpapproved	DATETIME	 NULL	COMMENT 'RFP<br>Approved',
	rentalpaidplan	DATETIME	 NULL	COMMENT 'Rental Paid<br>Plan',
	chequereleased	DATETIME	 NULL	COMMENT 'Cheque<br>Released',
	chequereceivedbylessorr	DATETIME	 NULL	COMMENT 'Cheque Received<br>by Lessorr',
	arorsubmittedtodito	DATETIME	 NULL	COMMENT 'AR/OR Submitted to Dito',
	rfpremarks	VARCHAR(200)	 NULL	COMMENT 'RFP Remarks',
	nationalpermitplan	DATETIME	 NULL	COMMENT 'National Permit<br>Plan',
	cncapplied	DATETIME	 NULL	COMMENT 'CNC<br>Applied',
	cncacquired	DATETIME	 NULL	COMMENT 'CNC<br>Acquired',
	dohapplied	DATETIME	 NULL	COMMENT 'DOH<br>Applied',
	dohacquired	DATETIME	 NULL	COMMENT 'DOH<br>Acquired',
	caapapplied	DATETIME	 NULL	COMMENT 'CAAP<br>Applied',
	caapacquired	DATETIME	 NULL	COMMENT 'CAAP<br>Acquired',
	natlcompletedplan	DATETIME	 NULL	COMMENT 'Natl Completed<br>Plan',
	lgupermitplan	DATETIME	 NULL	COMMENT 'LGU Permit<br>Plan',
	sbspapplied	DATETIME	 NULL	COMMENT 'SB/SP<br>Applied',
	sbspacquired	DATETIME	 NULL	COMMENT 'SB/SP<br>Acquired',
	mayorspermitsecured	DATETIME	 NULL	COMMENT 'Mayors Permit<br>Secured',
	lczoningapplied	DATETIME	 NULL	COMMENT 'LC/Zoning<br>Applied',
	zoningacquired	DATETIME	 NULL	COMMENT 'Zoning<br>Acquired',
	locationalacquired	DATETIME	 NULL	COMMENT 'Locational<br>Acquired',
	bpapplied	DATETIME	 NULL	COMMENT 'BP<br>Applied',
	bpsecured	DATETIME	 NULL	COMMENT 'BP<br>Secured',
	electricalpermitsecured	DATETIME	 NULL	COMMENT 'Electrical Permit<br>Secured',
	mechanicalpermitsecured	DATETIME	 NULL	COMMENT 'Mechanical Permit<br>Secured',
	electronicspermitsecured	DATETIME	 NULL	COMMENT 'Electronics Permit<br>Secured',
	fencingpermitsecured	DATETIME	 NULL	COMMENT 'Fencing Permit<br>Secured',
	sanitarypermitsecured	DATETIME	 NULL	COMMENT 'Sanitary Permit<br>Secured',
	fsecacquired	DATETIME	 NULL	COMMENT 'FSEC<br>Acquired',
	lgucompletedplan	DATETIME	 NULL	COMMENT 'LGU Completed<br>Plan',
	rtbplan	DATETIME	 NULL	COMMENT 'RTB<br>Plan',
	rtb	DATETIME	 NULL	COMMENT 'RTB',
	sbtsidoneplan	DATETIME	 NULL	COMMENT 'SBT/SI Done<br>Plan',
	soiltest	DATETIME	 NULL	COMMENT 'Soil test',
	soiltestreport	DATETIME	 NULL	COMMENT 'Soil test Report',
	soiltestreportapproved	DATETIME	 NULL	COMMENT 'Soil test Report Approved',
	dddsubmittedplan	DATETIME	 NULL	COMMENT 'DDD Submitted<br>Plan',
	dddapprovedplan	DATETIME	 NULL	COMMENT 'DDD Approved<br>Plan',
	towerheight	DECIMAL(10,7)	 NULL	COMMENT 'Tower Height<br>(m)',
	skomactual	DATETIME	 NULL	COMMENT 'SKOM',
	mobilizationplan	DATETIME	 NULL	COMMENT 'Mobilization<br>Plan',
	mobilizationstarted	DATETIME	 NULL	COMMENT 'Mobilization<br>Started',
	excavationplan	DATETIME	 NULL	COMMENT 'Excavation<br>Plan',
	excavationstarted	DATETIME	 NULL	COMMENT 'Excavation Started',
	rebarsplan	DATETIME	 NULL	COMMENT 'Rebars<br>Plan',
	rebarformworkre	DATETIME	 NULL	COMMENT 'Rebar Formwork<br>/Reinforcement',
	concreteplan	DATETIME	 NULL	COMMENT 'Foundation Concrete<br>Pouring Plan',
	concretepouringcompleted	DATETIME	 NULL	COMMENT 'Foundation Concrete<br>Pouring Completed',
	backfillingplan	DATETIME	 NULL	COMMENT 'Back Filling<br>Plan',
	mhroadconstr	DATETIME	 NULL	COMMENT 'MH and road construction',
	mhroadconstrcompl	DATETIME	 NULL	COMMENT 'MH and road construction Completed',
	perimeterwall 	DATETIME	 NULL	COMMENT 'Perimeter wall ',
	perimeterwallcompl	DATETIME	 NULL	COMMENT 'Perimeter wall<br>completed',
	electricalgroundingplan	DATETIME	 NULL	COMMENT 'Electrical&Grounding<br>Plan',
	electricalgroundinginstall	DATETIME	 NULL	COMMENT 'Electrical&Grounding<br>Installation',
	sitedevworkscompleted	DATETIME	 NULL	COMMENT 'Site Dev Works<br>Completed',
	patplan	DATETIME	 NULL	COMMENT 'PAT<br>Plan',
	patapproved	DATETIME	 NULL	COMMENT 'PAT<br>Approved',
	pacplan	DATETIME	 NULL	COMMENT 'PAC<br>Plan',
	provisionalacceptance	DATETIME	 NULL	COMMENT 'Provisional<br>Acceptance',
	facplan	DATETIME	 NULL	COMMENT 'FAC Plan',
	finalacceptance	DATETIME	 NULL	COMMENT 'Final<br>Acceptance',
	permanentpowerplan	DATETIME	 NULL	COMMENT 'Permanent Power Plan',
	permanentpowerapplied	DATETIME	 NULL	COMMENT 'Permanent Power Applied',
	jointsurveywithcoop	DATETIME	 NULL	COMMENT 'Joint Survey<br>with COOP',
	powerpaymentrfpsub	DATETIME	 NULL	COMMENT 'Power Payment<br>RFP Submitted',
	powerpaymentplan	DATETIME	 NULL	COMMENT 'Power Payment<br>Plan',
	powerpaymentrfprel	DATETIME	 NULL	COMMENT 'Power Payment<br>RFP Released',
	servicecontractsubmitted	DATETIME	 NULL	COMMENT 'Service Contract<br>Submitted',
	lineconstruction	DATETIME	 NULL	COMMENT 'Line<br>Construction',
	energizedplan	DATETIME	 NULL	COMMENT 'Energized<br>Plan',
	siteenergized	DATETIME	 NULL	COMMENT 'Site Energized',
	electricalpat	DATETIME	 NULL	COMMENT 'Electrical PAT',
	meterserialnumber	VARCHAR(100)	 NULL	COMMENT 'Meter Serial Number',
	electriccooperative	VARCHAR(100)	 NULL	COMMENT 'Electric Cooperative',
	extendt01	VARCHAR(100)	 NULL	COMMENT 'extendt01',
	extendt02	VARCHAR(100)	 NULL	COMMENT 'extendt02',
	extendt03	VARCHAR(100)	 NULL	COMMENT 'extendt03',
	extendt04	VARCHAR(100)	 NULL	COMMENT 'extendt04',
	extendt05	VARCHAR(100)	 NULL	COMMENT 'extendt05',
	extendt06	VARCHAR(100)	 NULL	COMMENT 'extendt06',
	extendt07	VARCHAR(100)	 NULL	COMMENT 'extendt07',
	extendt08	VARCHAR(100)	 NULL	COMMENT 'extendt08',
	extendt09	VARCHAR(100)	 NULL	COMMENT 'extendt09',
	extendt10	VARCHAR(100)	 NULL	COMMENT 'extendt10',
	extendt11	VARCHAR(100)	 NULL	COMMENT 'extendt11',
	extendt12	VARCHAR(100)	 NULL	COMMENT 'extendt12',
	extendt13	VARCHAR(100)	 NULL	COMMENT 'extendt13',
	extendt14	VARCHAR(100)	 NULL	COMMENT 'extendt14',
	extendt15	VARCHAR(100)	 NULL	COMMENT 'extendt15',
	extendt16	VARCHAR(100)	 NULL	COMMENT 'extendt16',
	extendt17	VARCHAR(100)	 NULL	COMMENT 'extendt17',
	extendt18	VARCHAR(100)	 NULL	COMMENT 'extendt18',
	extendt19	VARCHAR(100)	 NULL	COMMENT 'extendt19',
	extendt20	VARCHAR(100)	 NULL	COMMENT 'extendt20',
	extendi01	DECIMAL(10,0)	 NULL	COMMENT 'extendi01',
	extendi02	DECIMAL(10,0)	 NULL	COMMENT 'extendi02',
	extendi03	DECIMAL(10,0)	 NULL	COMMENT 'extendi03',
	extendi04	DECIMAL(10,0)	 NULL	COMMENT 'extendi04',
	extendi05	DECIMAL(10,0)	 NULL	COMMENT 'extendi05',
	extendi06	DECIMAL(10,0)	 NULL	COMMENT 'extendi06',
	extendi07	DECIMAL(10,0)	 NULL	COMMENT 'extendi07',
	extendi08	DECIMAL(10,0)	 NULL	COMMENT 'extendi08',
	extendi09	DECIMAL(10,0)	 NULL	COMMENT 'extendi09',
	extendi10	DECIMAL(10,0)	 NULL	COMMENT 'extendi10',
	extendi11	DECIMAL(10,0)	 NULL	COMMENT 'extendi11',
	extendi12	DECIMAL(10,0)	 NULL	COMMENT 'extendi12',
	extendi13	DECIMAL(10,0)	 NULL	COMMENT 'extendi13',
	extendi14	DECIMAL(10,0)	 NULL	COMMENT 'extendi14',
	extendi15	DECIMAL(10,0)	 NULL	COMMENT 'extendi15',
	extendi16	DECIMAL(10,0)	 NULL	COMMENT 'extendi16',
	extendi17	DECIMAL(10,0)	 NULL	COMMENT 'extendi17',
	extendi18	DECIMAL(10,0)	 NULL	COMMENT 'extendi18',
	extendi19	DECIMAL(10,0)	 NULL	COMMENT 'extendi19',
	extendi20	DECIMAL(10,0)	 NULL	COMMENT 'extendi20',
	extendd01	DATETIME	 NULL	COMMENT 'extendd01',
	extendd02	DATETIME	 NULL	COMMENT 'extendd02',
	extendd03	DATETIME	 NULL	COMMENT 'extendd03',
	extendd04	DATETIME	 NULL	COMMENT 'extendd04',
	extendd05	DATETIME	 NULL	COMMENT 'extendd05',
	extendd06	DATETIME	 NULL	COMMENT 'extendd06',
	extendd07	DATETIME	 NULL	COMMENT 'extendd07',
	extendd08	DATETIME	 NULL	COMMENT 'extendd08',
	extendd09	DATETIME	 NULL	COMMENT 'extendd09',
	extendd10	DATETIME	 NULL	COMMENT 'extendd10',
	extendd11	DATETIME	 NULL	COMMENT 'extendd11',
	extendd12	DATETIME	 NULL	COMMENT 'extendd12',
	extendd13	DATETIME	 NULL	COMMENT 'extendd13',
	extendd14	DATETIME	 NULL	COMMENT 'extendd14',
	extendd15	DATETIME	 NULL	COMMENT 'extendd15',
	extendd16	DATETIME	 NULL	COMMENT 'extendd16',
	extendd17	DATETIME	 NULL	COMMENT 'extendd17',
	extendd18	DATETIME	 NULL	COMMENT 'extendd18',
	extendd19	DATETIME	 NULL	COMMENT 'extendd19',
	extendd20	DATETIME	 NULL	COMMENT 'extendd20',
	extendd21	DATETIME	 NULL	COMMENT 'extendd21',
	extendd22	DATETIME	 NULL	COMMENT 'extendd22',
	extendd23	DATETIME	 NULL	COMMENT 'extendd23',
	extendd24	DATETIME	 NULL	COMMENT 'extendd24',
	extendd25	DATETIME	 NULL	COMMENT 'extendd25',
	extendd26	DATETIME	 NULL	COMMENT 'extendd26',
	extendd27	DATETIME	 NULL	COMMENT 'extendd27',
	extendd28	DATETIME	 NULL	COMMENT 'extendd28',
	extendd29	DATETIME	 NULL	COMMENT 'extendd29',
	extendd30	DATETIME	 NULL	COMMENT 'extendd30',
	extendd31	DATETIME	 NULL	COMMENT 'extendd31',
	extendd32	DATETIME	 NULL	COMMENT 'extendd32',
	extendd33	DATETIME	 NULL	COMMENT 'extendd33',
	extendd34	DATETIME	 NULL	COMMENT 'extendd34',
	extendd35	DATETIME	 NULL	COMMENT 'extendd35',
	extendd36	DATETIME	 NULL	COMMENT 'extendd36',
	extendd37	DATETIME	 NULL	COMMENT 'extendd37',
	extendd38	DATETIME	 NULL	COMMENT 'extendd38',
	extendd39	DATETIME	 NULL	COMMENT 'extendd39',
	extendd40	DATETIME	 NULL	COMMENT 'extendd40',
	extendd41	DATETIME	 NULL	COMMENT 'extendd41',
	extendd42	DATETIME	 NULL	COMMENT 'extendd42',
	extendd43	DATETIME	 NULL	COMMENT 'extendd43',
	extendd44	DATETIME	 NULL	COMMENT 'extendd44',
	extendd45	DATETIME	 NULL	COMMENT 'extendd45',
	extendd46	DATETIME	 NULL	COMMENT 'extendd46',
	extendd47	DATETIME	 NULL	COMMENT 'extendd47',
	extendd48	DATETIME	 NULL	COMMENT 'extendd48',
	extendd49	DATETIME	 NULL	COMMENT 'extendd49',
	extendd50	DATETIME	 NULL	COMMENT 'extendd50',
	extendn01	DECIMAL(8,6)	 NULL	COMMENT 'extendn01',
	extendn02	DECIMAL(8,6)	 NULL	COMMENT 'extendn02',
	extendn03	DECIMAL(8,6)	 NULL	COMMENT 'extendn03',
	extendn04	DECIMAL(8,6)	 NULL	COMMENT 'extendn04',
	extendn05	DECIMAL(8,6)	 NULL	COMMENT 'extendn05',
	extendn06	DECIMAL(8,6)	 NULL	COMMENT 'extendn06',
	extendn07	DECIMAL(8,6)	 NULL	COMMENT 'extendn07',
	extendn08	DECIMAL(8,6)	 NULL	COMMENT 'extendn08',
	extendn09	DECIMAL(8,6)	 NULL	COMMENT 'extendn09',
	extendn10	DECIMAL(8,6)	 NULL	COMMENT 'extendn10',
	extendn11	DECIMAL(8,6)	 NULL	COMMENT 'extendn11',
	extendn12	DECIMAL(8,6)	 NULL	COMMENT 'extendn12',
	extendn13	DECIMAL(8,6)	 NULL	COMMENT 'extendn13',
	extendn14	DECIMAL(8,6)	 NULL	COMMENT 'extendn14',
	extendn15	DECIMAL(8,6)	 NULL	COMMENT 'extendn15',
	extendn16	DECIMAL(8,6)	 NULL	COMMENT 'extendn16',
	extendn17	DECIMAL(8,6)	 NULL	COMMENT 'extendn17',
	extendn18	DECIMAL(8,6)	 NULL	COMMENT 'extendn18',
	extendn19	DECIMAL(8,6)	 NULL	COMMENT 'extendn19',
	extendn20	DECIMAL(8,6)	 NULL	COMMENT 'extendn20',
	sort				INTEGER				NULL	COMMENT 'Sort',
	status				CHAR(1)			NOT NULL	DEFAULT '0'COMMENT 'Status(0-normal 1-delete 2suspend 3error)',
	create_by			VARCHAR(64)			NULL	COMMENT 'Creator',
	create_date			DATETIME			NULL	COMMENT 'CreateDate',
	update_by			VARCHAR(64)			NULL	COMMENT 'Updater',
	update_date			DATETIME			NULL	COMMENT 'UpdateDate',
	remarks				VARCHAR(255)		NULL	COMMENT 'remarks',
	PRIMARY KEY (id)
) COMMENT = 'DCSite';